option nogil=True not required for ufuncs and gufuncs
numba/numba pull request #6445
Opened 2020-11-02 20:11 UTC by pradkrish

nogil=True option is not required for ufuncs and gufuncs. Print a UserWarning if it is provided.

2020-11-03 12:40 UTC, gmarkall requested changes
CUDA ufuncs don't release the GIL, for various reasons (some Python code needed around to setup arguments, kernel launch asynchrony, etc.). When trying to use `nogil=True` an error is produced. For example:

```python
@vectorize(nogil=True, target='cuda')
def f(x, y):
    return x + y
```

Gives:

```
KeyError: "cuda vectorize target does not support option: 'nogil'"
```

This is all fine with the functionality in this PR: However, I think the message in the warning is a little misleading - perhaps "ufuncs and gufuncs always release the GIL with the CPU target" would be more accurate?

2020-11-03 14:53 UTC, pradkrish commented
> This is all fine with the functionality in this PR: However, I think the message in the warning is a little misleading - perhaps "ufuncs and gufuncs always release the GIL with the CPU target" would be more accurate?

Thanks for the review, I have modified the warning.

2020-11-06 14:33 UTC, stuartarchibald reviewed
Thanks for the PR, just a couple of minor things to resolve else good to go! Thanks again!

2020-11-06 14:33 UTC, stuartarchibald commented on numba/np/ufunc/ufuncbuilder.py
> +                          "always releases GIL for CPU target")
Suggest using `numba.errors.NumbaWarning` as the warning category such that it's easier for users to filter out things from Numba.

2020-11-06 14:33 UTC, stuartarchibald commented on numba/np/ufunc/ufuncbuilder.py
> +                          "always releases GIL for CPU target")
```suggestion
            warnings.warn("The 'nogil' option is not required, ufuncs and gufuncs "
                          "always release the GIL on the CPU target")
```

2020-11-06 14:33 UTC, stuartarchibald commented on numba/tests/test_warnings.py
> +        @vectorize(nogil=True)
Would be good to check `guvectorize` as well given the error message mentions it?

2021-01-21 14:18 UTC, esc commented
@pradkrish just enquiring about the state of this PR, where is it at?

2023-03-28 01:55 UTC, closed without merging