Fix #6632 support alternative dtype string spellings
numba/numba pull request #6654
Opened 2021-01-20 19:46 UTC by stuartarchibald

As title. Support for alternative ways of spelling dtypes
with strings.

Fixes #6632

2021-01-26 00:27 UTC, sklam requested changes
The `numpy.dtype(str)` can handle building structured dtype, but this patch does not handle it correctly, leading to obscure error due to internal code error. I am suggesting this patch https://github.com/sklam/numba/commit/50ec513442d5bab33500bd662f5b81cc9ee60020 to fix the ICE and make structured dtype str spelling work for `np.zeros`.

2021-01-26 10:48 UTC, stuartarchibald commented on numba/core/typing/npydecl.py
> +            dtstr = dtype.literal_value
Good point, done in e51e82e

2021-01-28 16:25 UTC, sklam commented
@stuartarchibald, in the current state, it would allow the spelling of structured dtype as a str but it will lead to a internal error. Consider this patch (https://github.com/sklam/numba/commit/50ec513442d5bab33500bd662f5b81cc9ee60020) to fix it.

2021-02-01 14:53 UTC, stuartarchibald commented
> @stuartarchibald, in the current state, it would allow the spelling of structured dtype as a str but it will lead to a internal error. Consider this patch ([sklam@50ec513](https://github.com/sklam/numba/commit/50ec513442d5bab33500bd662f5b81cc9ee60020)) to fix it.

Good point, thanks for the patch, I've merged it in.

2021-02-01 20:52 UTC, sklam approved these changes

2021-02-02 00:33 UTC, merged