Adds tests for PR 5659
numba/numba pull request #6664
Opened 2021-01-27 00:46 UTC by sklam

Adds tests for 1D, 2D, 3D and C/F order arrays for parfors.

2021-01-27 19:56 UTC, DrTodd13 requested changes
This needed to be done.  Thanks for doing it.  Looks like it is running with no errors.

2021-01-27 19:56 UTC, DrTodd13 commented on numba/tests/test_parfors.py
> +    def gen_linespace_variants(self, ct):
Did you mean linespace or linspace?

2021-01-27 21:36 UTC, sklam commented on numba/tests/test_parfors.py
> +    def gen_linespace_variants(self, ct):
oops, it's linspace.

2021-02-03 12:24 UTC, stuartarchibald reviewed
Thanks for writing these extra tests @sklam, looks good, just one dead comment to remove and then can be merged.

2021-02-03 12:24 UTC, stuartarchibald commented on numba/parfors/parfor.py
>                          # only translate C order since we can't allocate F
remove this comment?

2021-02-03 16:12 UTC, DrTodd13 submitted a review, later dismissed

2021-02-03 16:12 UTC, DrTodd13 commented on numba/parfors/parfor.py
>                          # only translate C order since we can't allocate F
Yes, this comment should go.

2021-02-03 17:05 UTC, sklam commented
i've removed the dead comment

2021-02-03 17:16 UTC, stuartarchibald commented
> i've removed the dead comment

thanks.

2021-02-03 17:17 UTC, stuartarchibald approved these changes
Thanks for the patch(es). Looks good, great to see this working.

2021-02-03 21:10 UTC, merged