Enable negative indexing for cuda atomic operations
numba/numba pull request #6695
Opened 2021-02-06 09:50 UTC by ashutoshvarma

Ref #6496 

As titled, enables wraparound in CUDA atomic operations.

Instead of adding new tests, I modified existing add atomics tests `test_atomic_add_*` to prevent unnecessary redundancy in test code. 
If the separate test is a must then I can add that too.

2021-02-08 12:36 UTC, gmarkall requested changes
Many thanks for the PR! I think this is looking great in general, with just one suggestion / question:

- Tests pass for me locally with hardware (Quadro RTX 8000), the simulator, and under cuda-memcheck with no errors.
- The testing additions look good - I see that testing with negative indexing is only added for a subset of test cases, which I think covers the new functionality sufficiently without bloating the set of tests inordinately (as opposed to adding negative indexing to every single test).
- I'm happy with the additions being made to existing test cases, as it enables reuse of their code instead of either duplicating the rest of the test body or adding another level of indirection in the testing.
- The style of the changes looks good / seems to be in keeping with the surrounding code.


One thing I'd like to see - either I've missed it or it's not present - is testing of wraparound on arrays in global memory. In the test changes, I can only see tests for negative indexing on shared memory - if negative indexing on global memory is tested here, can you indicate where that testing is please? If not, would it be possible to add testing on negative indexing on global memory in a similar fashion to the testing on shared memory?

Many thanks again!

2021-02-09 14:56 UTC, ashutoshvarma commented
My bad, seems I missed global memory tests. I will update them in a minute.

2021-02-09 16:43 UTC, gmarkall commented
Many thanks for the update!

The test fail is just a conda error - could this have a re-run on Azure Pipelines please? (@esc / @stuartarchibald)

2021-02-09 16:53 UTC, esc commented
/azp run

2021-02-09 17:20 UTC, gmarkall approved these changes
Many thanks for adding the tests with global memory - they run fine for me locally with hardware, the simulator and cuda-memcheck. This now looks good to me!

@esc could this have a CUDA buildfarm run please?

2021-02-09 17:20 UTC, esc commented
@gmarkall seems like AZP fine this time around.

2021-02-09 17:21 UTC, esc commented
Running BF: `numba_smoketest_cuda_yaml_11`

2021-02-09 18:14 UTC, esc commented
BF passed on this.

2021-02-09 22:06 UTC, gmarkall commented
@stuartarchibald @sklam would you like to take a look at this before it goes RTM?

2021-02-19 14:25 UTC, stuartarchibald approved these changes
Thanks for the patch @ashutoshvarma looks good, thanks for reviewing @gmarkall

2021-02-19 23:58 UTC, merged