Avoid errors in array analysis for global tuples with non-int
numba/numba pull request #6727
Opened 2021-02-15 20:17 UTC by ehsantn

Closes #6726.

2021-02-15 20:38 UTC, DrTodd13 requested changes
Add a test that should work with a global tuple of ints?

Now that I think about it, if we compile a method and the global is a tuple of ints and after the function has executed we change the global to be something else entirely, then doesn't that invalidate the compilation?  Is Numba dispatcher keyed on globals that are used and their type?  Even if that were the case then doesn't this code bake in the value of the global at compilation time so if you change it to a different tuple of ints than the original then compilation wouldn't be triggered again and the baked in array analysis would be off.  So, unless you dispatched on not only the type but the value of the global then don't we have a potential problem here?

2021-02-15 22:28 UTC, ehsantn commented
I just assumed there is a test for the case that the new code supports, but I'll create some tests to be sure.

This is a known Numba limitation in general: https://numba.readthedocs.io/en/stable/reference/pysemantics.html#global-and-closure-variables

2021-02-15 22:45 UTC, DrTodd13 commented
@ehsantn As long as it is documented that way it is fine then.  Thanks for the patch.

2021-02-15 23:26 UTC, ehsantn commented
@DrTodd13 added a test for a global tuple of ints.

2021-02-16 14:29 UTC, stuartarchibald reviewed
Thanks for the patch, couple of typos else looks good.

2021-02-16 14:29 UTC, stuartarchibald commented on numba/tests/test_array_analysis.py
> +
```suggestion
```

2021-02-16 14:29 UTC, stuartarchibald commented on numba/tests/test_array_analysis.py
> +        """make sure a gobal value with non-integers does not cause errors
```suggestion
        """make sure a global tuple with non-integer values does not cause errors
```

2021-02-16 15:43 UTC, stuartarchibald approved these changes
Thanks for the fixes, looks good.

2021-02-16 23:16 UTC, merged