ParallelAccelerator no long will convert StaticSetItem to SetItem because record arrays require StaticSetItems.
numba/numba pull request #6801
Opened 2021-03-05 23:47 UTC by DrTodd13

Resolves #6704.

2021-03-08 23:02 UTC, sklam requested changes
I've suggested additional test to improve coverage.

2021-03-08 23:51 UTC, DrTodd13 commented on numba/tests/test_parfors.py
> +
Done.

2021-03-09 14:16 UTC, stuartarchibald commented
Open/Close was to try and re-start the RTD docs build.

2021-03-22 17:10 UTC, stuartarchibald reviewed
Thanks for the patch, couple of minor things else looks good.

2021-03-22 17:10 UTC, stuartarchibald commented on numba/tests/test_parfors.py
> +                           np.empty(shape=1, dtype=state_dtype),
```suggestion
                           np.zeros(shape=1, dtype=state_dtype),
```
just in case `empty` contains a `1`!

2021-03-22 17:10 UTC, stuartarchibald commented on numba/parfors/parfor.py
> +
```suggestion


```

2021-03-23 12:48 UTC, stuartarchibald approved these changes
Thanks for the patch and fixes. @sklam's unit test is added so I think everything is resolved.

2021-03-23 22:55 UTC, sklam approved these changes

2021-03-23 22:55 UTC, merged