Remove illegal "debug" kw argument
numba/numba pull request #6834
Opened 2021-03-17 03:29 UTC by shaunc

Fix for https://github.com/numba/numba/issues/6615

Removes illegal argument from call to  `FakeCUDAKernel`. Hard to trigger in test -- but currently these lines are untested and clearly illegal, as `FakeCUDAKernel` does not take the `debug` keyword.

2021-03-17 10:13 UTC, stuartarchibald commented
Thanks for the PR @shaunc.

@gmarkall please could you review, thanks.

2021-03-17 11:14 UTC, gmarkall requested changes
Thanks for the fix! This passes tests for me with the simulator and hardware.

I wasn't able to work out exactly what to do with conftest.py to check this (getting errors such as `INTERNALERROR> ValueError: no option named '--cudasim'` when running `pytest`), but I'd suggest the following as a test for this:

```diff
From 2c9313f74360abc9f4af27b855d0cf7f357a55b1 Mon Sep 17 00:00:00 2001
From: Graham Markall <gmarkall@nvidia.com>
Date: Wed, 17 Mar 2021 11:10:44 +0000
Subject: [PATCH] Test debug kwarg to cuda.jit with simulator

---
 numba/cuda/tests/cudapy/test_cuda_jit_no_types.py | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/numba/cuda/tests/cudapy/test_cuda_jit_no_types.py b/numba/cuda/tests/cudapy/test_cuda_jit_no_types.py
index 49018b70e..b57e7649c 100644
--- a/numba/cuda/tests/cudapy/test_cuda_jit_no_types.py
+++ b/numba/cuda/tests/cudapy/test_cuda_jit_no_types.py
@@ -1,6 +1,7 @@
 from numba import cuda
 import numpy as np
 from numba.cuda.testing import CUDATestCase
+from numba.tests.support import override_config
 import unittest
 
 
@@ -76,6 +77,14 @@ class TestCudaJitNoTypes(CUDATestCase):
 
         self.assertEqual(b[0], (a[0] + 1) + (2 + 1))
 
+    def test_jit_debug_simulator(self):
+        # Ensure that the jit decorator accepts the debug kwarg when the
+        # simulator is in use - see Issue #6615.
+        with override_config('ENABLE_CUDASIM', 1):
+            @cuda.jit(debug=True)
+            def f(x):
+                pass
+
 
 if __name__ == '__main__':
     unittest.main()
-- 
2.28.0

```

This additional test fails on master with:

```
$ python -m numba.runtests numba.cuda.tests.cudapy.test_cuda_jit_no_types
...E
======================================================================
ERROR: test_jit_debug_simulator (numba.cuda.tests.cudapy.test_cuda_jit_no_types.TestCudaJitNoTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_cuda_jit_no_types.py", line 83, in test_jit_debug_simulator
    def f(x):
  File "/home/gmarkall/numbadev/numba/numba/cuda/decorators.py", line 108, in autojitwrapper
    return FakeCUDAKernel(func, device=device,
TypeError: __init__() got an unexpected keyword argument 'debug'

----------------------------------------------------------------------
Ran 4 tests in 0.292s

FAILED (errors=1)
```

but passes with your patch.

2021-03-17 15:37 UTC, shaunc commented
Thanks for the test! For the conftest to work, you also need `pytest_addoption` ... and probably that isn't what is wanted either (we want to test unconditionally -- not depending on an option, and the test should be isolated from other tests). 

I meant that more as an illustration of how I was managing to trigger this problem (though I'm not actually sure in detail what is happening). Still -- the PR does fix the problem for me, so was hopeful it could find its way into the repo.

2021-03-17 15:48 UTC, shaunc commented
\[Ok -- @gmarkall -- added your test to PR; Thanks!\]

2021-03-17 15:58 UTC, gmarkall submitted a review, later dismissed
This now looks good to me - many thanks for the fixes!

2021-03-17 19:23 UTC, stuartarchibald commented
@shaunc thanks for the patch, any chance you could fix this `flake8` error please so that CI succeeds? https://dev.azure.com/numba/numba/_build/results?buildId=8269&view=logs&j=9b1c419d-97bd-5aaf-47ca-b83be1ff9bc1&t=d1ed00e6-cc06-521a-e00c-4f5e4a0f55c5&l=84

Many thanks.


@gmarkall thanks for reviewing.

2021-03-18 17:44 UTC, gmarkall approved these changes
Thanks for the fix - this still looks good to me.

@stuartarchibald Do you want a buildfarm run?

2021-03-22 17:38 UTC, stuartarchibald commented
Think there's another `debug=` here https://github.com/numba/numba/blob/e0ffba72656d317d8ecd4396224d04c9088a39ae/numba/cuda/decorators.py#L76-L80 ?

2021-03-22 18:34 UTC, shaunc commented
Ok -- got that one too...

2021-03-22 20:51 UTC, gmarkall approved these changes
This still looks good to me with the additional change.

@stuartarchibald pointed out to me that there are reasons why the original issue may not manifest itself in all configurations, particularly if a driver is not installed:

> when you do `@cuda.jit` under CUDASIM and DO NOT have a driver, the `cuda.jit` decorator is the one from `numba.cuda.simulator.api`, and that has a `debug=`  flag in the `jit()` definition, whereas if you had the driver, you'd get `numba.cuda.jit` as your `jit()` definition which is broken, and the `numba.cuda.simulator.api.jit`  function does create a `FakeCUDAKernel` but it doesn't get passed the `debug` flag.

As this PR makes an improvement by fixing cases that presently don't work, I'm inclined not to suggest further changes now given that a whole set of changes to the `jit` decorator to make the logic more explicit and linear are planned for the near future (originally highlighted by the fact that `lineinfo` from PR #6802 "magically" worked, and reinforced by the discussion on this issue).

2021-03-31 11:46 UTC, gmarkall commented
@stuartarchibald Are you happy for this to go in, following a successful buildfarm run?

2021-03-31 12:41 UTC, stuartarchibald commented
> @stuartarchibald Are you happy for this to go in, following a successful buildfarm run?

Yes, I think this is a fix solely based on inspection of the source/issue reported, the `debug` flag is evidently erroneous in various cases. Also, as noted, the logic needs looking at more generally but that's not a task for this PR. Thanks for reviewing @gmarkall.

2021-04-09 11:47 UTC, stuartarchibald commented
Buildfarm ID: `numba_smoketest_cuda_yaml_38`.

2021-04-09 12:22 UTC, stuartarchibald commented
> Buildfarm ID: `numba_smoketest_cuda_yaml_38`.

Passed.

2021-04-09 12:22 UTC, stuartarchibald commented
@shaunc Congratulations on your first contribution to Numba!

2021-04-09 23:09 UTC, merged