Added NPM to Glossary and linked to mentions
numba/numba pull request #7283
Opened 2021-08-05 16:19 UTC by nihalshetty-boop

## Reference an existing issue
Fixes #7282

## Description
I've added `NPM` to the definition of [nopython mode](https://numba.readthedocs.io/en/stable/glossary.html#term-nopython-mode) in `glossary.rst`. Also linked mentions of `NPM` in three places, having five occurences in total. Thanks a lot to @HPLegion and @stuartarchibald for helping me with this issue! 

- I've read the [Contributing Guide](https://numba.pydata.org/numba-doc/dev/developer/contributing.html) before working on this.

2021-08-05 16:40 UTC, stuartarchibald commented
Thanks for the patch @nihalshetty-boop, it's queued for review.

2021-08-05 16:43 UTC, HPLegion commented
Glad I could help :-)

Rendered docs seem to behave as expected: https://numba--7283.org.readthedocs.build/en/7283/developer/numba-runtime.html?highlight=npm

2021-08-05 17:19 UTC, stuartarchibald reviewed
Thanks for the patch. I think the proposed changes look good, but please could the lines be wrapped to 80 chars? Many thanks.

2021-08-05 17:43 UTC, nihalshetty-boop commented
>but please could the lines be wrapped to 80 chars? 

I'm sorry I didn't quite understand, can you elaborate on this?

2021-08-05 19:25 UTC, nihalshetty-boop commented
> > but please could the lines be wrapped to 80 chars?
> 
> @stuartarchibald I'm sorry I didn't quite understand, can you elaborate on this? Should I decrease the character count of the PR Description to 80 characters?

Understood the issue and fixed in commit `Wrapped Line Characters to <= 80`.

2021-08-06 06:10 UTC, HPLegion requested changes

2021-08-06 06:10 UTC, HPLegion commented on docs/source/developer/numba-runtime.rst
> +Those functions should be moved to NRT.
When you fixed the line wrapping here, you accidentally broke the indentation. That is why one of the tests failed. (You can also see the effect of this by watching the "Github rendered" version or the read the docs build).

I suggest you click your way through the failed test pipeline to see how the output can help with finding what's broken :-)

2021-08-06 06:13 UTC, HPLegion commented
(Right now the latest round of failed tests is shown in the bottom because you have not pushed any new commits yet. In general you can inspect previous test runs by clicking on the small red cross :x: or green check mark :heavy_check_mark: next to the fingerprint of the commit)

2021-08-06 06:50 UTC, nihalshetty-boop commented
Great, thank you for helping me out, I've corrected the indentation now :)

2021-08-06 07:26 UTC, HPLegion approved these changes
This looks good to me.
- I have manually verified that the new `NPM` cross references are working on ReadTheDocs.
- The indentation error is fixed and the respective part now renders correctly

There are a couple of cosmetic changes that could be made to this file (line length violations, double spaces) But in my eyes they are not really a part of this PR, so I would personally avoid mixing them in here.

2021-08-06 07:45 UTC, nihalshetty-boop commented
@HPLegion Awesome! If an issue could be raised about
>There are a couple of cosmetic changes that could be made to this file (line length violations, double spaces)

I would be interested in working on it. I'm not sure if I can raise issues as a first time contributor.

2021-08-06 07:55 UTC, HPLegion commented
> I would be interested in working on it. I'm not sure if I can raise issues as a first time contributor.

Anyone can - and should - open issues if they see any :-)
For a maintenance issue like this, where you already know what the problem is, an issue is probably not even needed. You can just fix it and make a PR explaining what you did and why (in my opinion).

That said, I'd wait for feedback from a core maintainer here, to see how they feel about this. Maybe they actually prefer if those changes are integrated here.

Secondly, if you start working on this now, before this PR is merged into master, then you will likely run into merge conflicts with your cosmetics branch later, because some of the changes will touch on the same lines as the one in this PR. If you see that as an annoyance or as a possibility to learn dealing with conflicts, is up to you to decide ;-)

2021-08-06 08:11 UTC, nihalshetty-boop commented
Yes, it's better to wait till this PR has been merged 👍

2021-08-06 09:37 UTC, stuartarchibald commented
@HPLegion many thanks for providing guidance throughout this PR and for reviewing it, it's much appreciated.

@nihalshetty-boop, @HPLegion , I'd say it's fine to just open PRs for cosmetic fixes to e.g. docs that are quick to do and unlikely to be controversial. It's entirely fine to open PRs for anything, but obviously if there's a lot of work involved it's generally a good idea to open an issue about it first so as to gather feedback prior to starting the work to ensure that the PR has a good chance of being merged etc.

RE additional changes. To save merge conflict issues I'd either wait for this PR to be merged (probably in the merge window later today) or to base a new PR off this branch and then when this patch is merged git/github will just figure out the diff.

2021-08-06 09:37 UTC, stuartarchibald approved these changes
Thanks for the patch.

2021-08-06 09:38 UTC, stuartarchibald commented
@nihalshetty-boop Congratulations on your first contribution to Numba!

2021-08-06 09:58 UTC, nihalshetty-boop commented
Thank you!

2021-08-09 20:33 UTC, merged