Fix issues with package dependencies.
numba/numba pull request #7626
Opened 2021-12-07 10:25 UTC by stuartarchibald

* Removes the unconditional installation of ipykernel (the
  "VANILLA_INSTALL" must have no additional packages).
* Fixes the package requirements, ipython_genutils is a dependency
  of ipykernel so does not need listing separately.
* Updates the associated comments.

2021-12-07 10:28 UTC, stuartarchibald commented
Note:
```
$ conda search ipykernel --info
```
Sample output:
```
ipykernel 6.4.1 py39h06a4308_1
------------------------------
file name   : ipykernel-6.4.1-py39h06a4308_1.conda
name        : ipykernel
version     : 6.4.1
build       : py39h06a4308_1
build number: 1
size        : 194 KB
license     : BSD-3-Clause
subdir      : linux-64
url         : https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-6.4.1-py39h06a4308_1.conda
md5         : bfb323ce72a0787939d2412529a8063f
timestamp   : 2021-10-06 15:38:18 UTC
dependencies: 
  - debugpy >=1,<2.0
  - ipython >=7.23.1,<8.0
  - ipython_genutils
  - jupyter_client <8.0
  - matplotlib-inline >=0.1.0,<0.2.0
  - python >=3.9,<3.10.0a0
  - tornado >=4.2,<7.0
  - traitlets >=4.1.0,<6.0

```

2021-12-07 10:29 UTC, stuartarchibald commented
xref #7345 for the new tests that introduced this dependency.

2021-12-08 10:16 UTC, esc requested changes
I think that `ipython_genutils` is missing from the install command.

I would also suggest to add `ipython_genutils` and `ipykernel` to the dependency list at:

https://numba.readthedocs.io/en/stable/user/installing.html#dependency-list

Tracking optional dependencies in CI scripts is somewhat suboptimal.

2021-12-08 10:16 UTC, esc commented on buildscripts/incremental/setup_conda_environment.sh
> +    $CONDA_INSTALL ${EXTRA_CHANNELS} cffi jinja2 ipython pygments pexpect ipykernel
```suggestion
    $CONDA_INSTALL ${EXTRA_CHANNELS} cffi jinja2 ipython ipython_genutils pygments pexpect ipykernel
```

2021-12-08 11:35 UTC, esc commented
> > I think that `ipython_genutils` is missing from the install command.
> 
> Note: [#7626 (comment)](https://github.com/numba/numba/pull/7626#issuecomment-987783977), `ipython_genutils` is a hard dependency of `ipykernel`.

Oh yes, I missed that.

> > I would also suggest to add `ipython_genutils` and `ipykernel` to the dependency list at:
> > https://numba.readthedocs.io/en/stable/user/installing.html#dependency-list
> > Tracking optional dependencies in CI scripts is somewhat suboptimal.
> 
> I don't think these are optional dependencies for Numba, nothing is gained from a user's perspective by installing them and the Numba compiler itself does not use them? These packages are used solely in the test suite to check various features. Another example is `pexpect`, the test suite needs this to drive the `gdb` integration testing, but Numba has no reliance on it, optional or otherwise. The conda build `meta.yaml` test section reflects this. If anything I'd suggest the docs might need an "Optional test time" section?

Makes sense. Probably not important for now.

2021-12-08 11:35 UTC, esc submitted a review, later dismissed

2021-12-09 21:51 UTC, esc commented
@stuartarchibald thank you for the patches!

2021-12-09 22:00 UTC, sklam approved these changes
LGTM

2021-12-10 20:52 UTC, merged