Added the interval example as doctest
numba/numba pull request #8220
Opened 2022-07-04 10:40 UTC by kc611

Continuation of: https://github.com/numba/numba/pull/5113

Original code by @eric-wieser

2022-07-04 10:47 UTC, kc611 commented on numba/tests/doc_examples/test_interval_example.py
> +            is_error_ptr = cgutils.alloca_once_value(c.builder,
The original `fail_obj` logic over here that replaced the object by a null object of the same type wasn't working. Not sure if that was how to do it or if it's required, pseudocode:

```
       ret_ptr = cgutils.alloca_once(c.builder, c.context.get_value_type(typ))
       fail_obj = c.context.get_constant_null(typ)

       with ExitStack() as stack:
           if fail:
               c.builder.store(fail_obj, ret_ptr)
           interval = cgutils.create_struct_proxy(typ)(c.context, c.builder)
           c.builder.store(interval._getvalue(), ret_ptr)
       return NativeValue(c.builder.load(ret_ptr), is_error=c.builder.load(is_error_ptr))
```

2022-07-04 10:53 UTC, kc611 commented on numba/tests/doc_examples/test_interval_example.py
> +            with ExitStack() as stack:
I remember @stuartarchibald suggesting we could have a generalized solution for such Exit-if-null strategy. The main issue with this particular approach is that we can't abstract out the context definitions and exits. 

Is there anything that comes to mind regarding how we could do this with a more simpler method ?

2022-07-25 10:58 UTC, esc commented
/azp run

2022-07-25 11:35 UTC, eric-wieser commented
Any chance you could split this PR into two: the doc-test-ification, and the the change I suggested in the other PR? It would make it easier to see the effect of my changes.

2022-07-25 14:23 UTC, kc611 commented
Good idea. It'll be easier to review too.

2022-07-25 16:07 UTC, eric-wieser commented on docs/source/extending/interval-example.rst
> +class that it does not internally supported. This will allow:
```suggestion
class that it does not internally support. This will allow:
```

2022-07-25 16:09 UTC, eric-wieser commented on numba/tests/doc_examples/test_interval_example.py
> +# "magictoken" is used for markers as beginning and ending of example text.
```suggestion
"""
This test is used by `docs/source/extending/interval-example.rst`.

The "magictoken" comments are used as markers for the beginning and ending of example code.
"""
```

2022-07-25 16:09 UTC, eric-wieser submitted a review, later dismissed
I haven't checked that the old and new python code are identical, but this looks like a very nice way to extract a doctest.

2022-07-27 13:18 UTC, esc commented
@kc611 is there any chance you could include @eric-wieser 's original commit as a basis, in order to preserve their attribution?

2022-07-27 13:24 UTC, eric-wieser commented
I don't think any of this patch is my contribution at this point, only the next one is

2022-07-27 15:39 UTC, esc commented
/azp run

2022-07-27 15:53 UTC, esc requested changes
just some final flake8 nitpick

2022-07-27 15:53 UTC, esc commented on numba/tests/doc_examples/test_interval_example.py
> +The "magictoken" comments are used as markers for the beginning and ending of example code.
Sphinx is complaing here:

numba/tests/doc_examples/test_interval_example.py:4:81: E501 line too long (91 > 80 characters)

```suggestion
The "magictoken" comments are used as markers for the beginning and ending of
example code.
```

2022-07-27 17:25 UTC, esc commented
@kc611 thank you for the patch!

2022-07-27 17:25 UTC, esc approved these changes

2022-07-27 22:09 UTC, merged