refactor np.where to use overload
numba/numba pull request #8258
Opened 2022-07-19 17:43 UTC by guilhermeleobas

xref: #8254 

* Refactor `np.where` to use `@overload`
* Add NumPy tests
* Add type check for supported types + tests

2022-07-20 17:49 UTC, apmasell submitted a review, later dismissed

2022-07-21 03:06 UTC, guilhermeleobas commented
Thanks for the review, @apmasell

2022-10-18 09:46 UTC, stuartarchibald commented
@guilhermeleobas thanks for the patch. In the interests of making this easier to review, perhaps split the API refactoring and the addition of new functionality into separate patches?

2022-11-08 14:07 UTC, stuartarchibald commented
@guilhermeleobas please could you resolve the conflicts against `main`? Many thanks.

2022-11-17 14:33 UTC, kc611 requested changes
The code looks functionally good and well-written. There are mostly issues with handling of `None` and a few nitpicks but otherwise it LGTM.

2022-11-17 14:33 UTC, kc611 commented on numba/tests/test_array_methods.py
> +        np.testing.assert_equal(cfunc(c, b, a), r)
We could add some tests involving `None` ?

2022-11-21 17:46 UTC, guilhermeleobas commented on numba/np/arraymath.py
> +                layout = 'C'
I just kept the original behavior, which assigns the layout to `C`:
https://github.com/numba/numba/blob/3bee7be27b3672519a3e7660192dbb061ab424f4/numba/core/typing/npydecl.py#L710-L715

2022-11-21 19:38 UTC, guilhermeleobas commented on numba/tests/test_array_methods.py
> +        cfunc = jit(nopython=True)(pyfunc)
I'm following the convention used in the test file.

2022-11-21 19:39 UTC, guilhermeleobas commented on numba/np/arraymath.py
> +        return _where_cond_none_none
Supporting `None` inputs will be tricky. I'll try to address this in the following days.

2022-11-30 15:17 UTC, stuartarchibald reviewed
Thanks for the patch, this largely looks good, great to see the NumPy tests passing too. I've left a few comments inline, once resolved should be good to merge.

2022-12-02 13:49 UTC, guilhermeleobas commented on numba/np/arraymath.py
> +        msg = 'either both or neigher of "x" or "y" should be given'
This is actually the message that NumPy uses:

```python
>>> import numpy as np
>>>a = np.arange(5)
>>> np.where(a, a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in where
ValueError: either both or neither of x and y should be given
```

2022-12-02 14:04 UTC, guilhermeleobas commented on numba/np/arraymath.py
> +        res[idx] = x[idx] if c else y[idx]
Is there anything we can do in this case?

2022-12-02 14:39 UTC, stuartarchibald commented on numba/np/arraymath.py
> +        msg = 'either both or neigher of "x" or "y" should be given'
Thanks for checking, I guess we should leave it then.

2022-12-05 23:07 UTC, guilhermeleobas commented on numba/np/arraymath.py
> +        return _where_cond_none_none
I've changed the code to not use `None` as default value.

2022-12-05 23:10 UTC, guilhermeleobas commented
@kc611 @stuartarchibald, would you folks be ok with not supporting `None` inputs in this patch? Current patch fails with such values as `np.asarray(None)` is not supported.

2022-12-06 13:15 UTC, stuartarchibald approved these changes
Thanks for the updates @guilhermeleobas, think they address everything in the review. I'm inclined to leave the issue with unifying 'unusual' array types for now unless you feel strongly otherwise. Thanks again!

2022-12-06 21:15 UTC, merged