Add get_max_threads_per_block method to Dispatcher
numba/numba pull request #8348
Opened 2022-08-15 05:14 UTC by testhound

This pull request partially address issue: https://github.com/numba/numba/issues/6448 by adding support for retrieving the maximum threads per block utilized from the Dispatcher.

2022-08-15 05:14 UTC, testhound commented
gpuci run tests

2023-01-10 12:20 UTC, gmarkall requested changes
Thanks for the PR. Some small comments on the diff to address, and a merge from master needed.

2023-01-11 04:16 UTC, testhound commented
@gmarkall I updated the PR with all your recommendations.

2023-01-11 11:22 UTC, gmarkall commented
@testhound Do you know what is going on with the tests?

2023-01-11 15:02 UTC, testhound commented
@gmarkall I had an error in kernet.rst that is now fixed.

2023-01-13 16:42 UTC, testhound commented
gpuci run tests

2023-02-16 12:12 UTC, gmarkall requested changes
Many thanks for the updates. One small suggestion on the diff, then I think this should be good to merge.

2023-02-16 12:12 UTC, gmarkall commented on numba/cuda/dispatcher.py
> +        the kernel failing to launch
```suggestion
        the kernel failing to launch.
```

2023-02-16 18:07 UTC, testhound commented
gpuci run tests

2023-02-24 16:40 UTC, gmarkall approved these changes
Thanks for the update!

2023-02-25 00:17 UTC, merged