Bump NumPy pinning in meta.yaml
numba/numba pull request #8414
Opened 2022-09-01 22:05 UTC by sklam

as titled

2022-09-01 22:06 UTC, sklam commented
`numba_smoketest_cpu_yaml_126`

2022-09-02 00:43 UTC, sklam commented on CHANGE_LOG
> +*
```suggestion

```

2022-09-02 00:44 UTC, sklam commented on CHANGE_LOG
> +Version 0.56.1 (1 September, 2022)
```suggestion
* PR `#8414 <https://github.com/numba/numba/pull/8413>`_: Hotfix for 0.56.2 (`Siu Kwan Lam <https://github.com/sklam>`_)

Version 0.56.1 (1 September, 2022)
```

2022-09-02 00:52 UTC, esc requested changes
The URL appears to have been shortened.

2022-09-02 00:52 UTC, esc commented on CHANGE_LOG
> +* PR `#8414 <https://github.com//pull/8413>`_: Hotfix for 0.56.2 (`Siu Kwan Lam <https://github.com/sklam>`_)
```suggestion
* PR `#8414 <https://github.com/numba/numba/pull/8413>`_: Hotfix for 0.56.2 (`Siu Kwan Lam <https://github.com/sklam>`_)
```

2022-09-02 01:04 UTC, esc approved these changes
Can be merged when public CI passes.

2022-09-02 02:30 UTC, merged