Testhound/cuda array reshape 7528
numba/numba pull request #8458
Opened 2022-09-22 21:16 UTC by testhound

This PR adds the ability to perform array reshaping in CUDA kernels and addresses issue [](https://github.com/numba/numba/issues/7528)

2022-09-22 21:17 UTC, testhound commented
gpuci run tests

2022-09-26 15:49 UTC, testhound commented
gpuci run tests

2023-02-14 12:52 UTC, gmarkall commented
Note: I've updated the description so it links to the issue.

2023-02-14 12:55 UTC, gmarkall commented
cc @shaunc as I think this addresses the use case mentioned in #8740.

2023-02-15 06:26 UTC, testhound commented
gpuci run tests

2023-02-15 06:35 UTC, testhound commented
gpuci run tests

2023-02-15 07:00 UTC, testhound commented
gpuci run tests

2023-02-15 07:56 UTC, testhound commented
@gmarkall merge conflicts resolved.

2023-02-16 11:52 UTC, gmarkall requested changes
Thanks for the PR. Without diving into the details / minutiae of the PR initially, I wonder if there are a few things we ought to think about changing:

- The code in `cuda_helperlib.cu` is all lifted verbatim from `_helperlib.c`, save for a couple of small modifications for CUDA. Rather than carrying round two copies of these functions (which ideally we'd keep in sync but not have to worry about manually syncing) can we rework this so that the same code can be used for both the CPU and CUDA targets?
- The testing is a little light - are there reshaping tests in the CPU target that can be reused?
- The code appending the cuda_helperlib.c file to the link duplicates the code appending the float16 wrappers to the link - I think this could be simplified so we don't need two copies of the logic.

2023-03-23 23:20 UTC, testhound commented
gpuci run tests

2023-03-24 00:07 UTC, testhound commented
@gmarkall changes incorporated and ready for review.

2023-05-26 21:40 UTC, testhound commented
gpuci run tests

2023-05-26 22:13 UTC, testhound commented
gpuci run tests

2023-05-26 23:01 UTC, testhound commented
@gmarkall merged with main to fix conflicts. Ready for review.

2023-06-02 19:42 UTC, testhound commented
gpuci run tests

2025-01-02 10:40 UTC, closed without merging