[WIP] Added initial typed set implementation
numba/numba pull request #8741
Opened 2023-02-06 14:56 UTC by kc611

As titled, this PR adds initial support for `typed.set`s

2023-02-20 22:06 UTC, sklam reviewed
I took a brief look and looks good. Thoughts on adding test and support for reference-counted objects?

2023-03-09 09:20 UTC, kc611 commented
@sklam I've added basic refcounted object support and tests in [77bcead](https://github.com/numba/numba/pull/8741/commits/77bceadb0b5126aaf31a282981f30fdcba402277), let me know if it looks good.

2023-05-10 03:01 UTC, lgray commented
Just to note - to fix #8942 could you please remove the sentries in type dict that cause sets to raise an exception as dict keys/values? If using typed Set bypasses this, please ignore me. :-)

2023-05-13 14:23 UTC, lgray commented
Hey, so trying out the code in my issue works pretty well. I ran into a few snags. Here's the functioning code:
```python3
import numba as nb

_coords_kernel_input_type = nb.types.Set(nb.types.UniTuple(nb.types.int64, 1), reflected=True)
_coords_kernel_keyval_type = nb.types.Tuple([nb.types.unicode_type, nb.types.int64])
_coords_kernel_return_type = nb.types.DictType(
    _coords_kernel_keyval_type,
    nb.types.Set(_coords_kernel_keyval_type),
)

@nb.jit(_coords_kernel_return_type(_coords_kernel_input_type, nb.types.unicode_type, nb.types.unicode_type), nopython=True)
def _coords_single_input_kernel(output_blocks, output_key, index_key):
    output = {}
    for out_coord in output_blocks:
        output[(output_key, out_coord[0])] = {(index_key, out_coord[0])}
    return output



test_input = {(1,), (2,), (3,), (4,)}
test_key = "test_key"
test_index_key = "test_index_key"

test_out = _coords_single_input_kernel(test_input, test_key, test_index_key)

print(test_out)
```

I ran into some snags because I cannot do things related to hinting the dict type (which is nice for compilation speed):
```python3
output = nb.typed.Dict.empty(
    _coords_kernel_keyval_type,
    nb.types.Set(_coords_kernel_keyval_type),
)
```
which results in a compilation error:
```
Invalid use of <class 'numba.core.types.containers.Set'> with parameters (typeref[Tuple(unicode_type, int64)])
No type info available for <class 'numba.core.types.containers.Set'> as a callable.
During: resolving callee type: typeref[<class 'numba.core.types.containers.Set'>]
During: typing of call at repro.py (14)


File "repro.py", line 14:
def _coords_single_input_kernel(output_blocks, output_key, index_key):
    <source elided>
        _coords_kernel_keyval_type,
        nb.types.Set(_coords_kernel_keyval_type),
```

2023-05-13 14:24 UTC, lgray commented
I also had to make a change to the sentry in python to allow dict to accept sets as arguments:
```diff
diff --git a/numba/core/types/containers.py b/numba/core/types/containers.py
index 243988abc..ff164de4c 100644
--- a/numba/core/types/containers.py
+++ b/numba/core/types/containers.py
@@ -693,11 +693,11 @@ class ListTypeIteratorType(SimpleIteratorType):
         super(ListTypeIteratorType, self).__init__(name, yield_type)
 
 
-def _sentry_forbidden_types(key, value):
+def _sentry_forbidden_types(key, value, forbidden=(Set, List)):
     # Forbids List and Set for now
-    if isinstance(key, (Set, List)):
+    if isinstance(key, forbidden):
         raise TypingError("{} as key is forbidden".format(key))
-    if isinstance(value, (Set, List)):
+    if isinstance(value, forbidden):
         raise TypingError("{} as value is forbidden".format(value))
 
 
@@ -716,7 +716,7 @@ class DictType(IterableType, InitialValue):
         if isinstance(valty, (Optional, NoneType)):
             fmt = "Dict.value_type cannot be of type {}"
             raise TypingError(fmt.format(valty))
-        _sentry_forbidden_types(keyty, valty)
+        _sentry_forbidden_types(keyty, valty, forbidden=(List))
         self.key_type = keyty
         self.value_type = valty
         self.keyvalue_type = Tuple([keyty, valty])
```

2023-05-19 17:29 UTC, lgray commented
@kc611 is there any more information you would like in order to proceed?

2023-05-22 07:08 UTC, kc611 commented
Hi @lgray, Sorry for the late response. 

As for your suggested change, I think the scope of the changes you suggest differs from the intent of this PR. The suggested changes are typed-dict specific, whereas this PR intends to add core support for typed-set. 

As a result, I've made #8973, where this discussion can be continued.

2023-05-22 13:18 UTC, stuartarchibald commented
RE `_sentry_forbidden_types`, this code guards against the use of "reflected" container instances as members of "typed" container instances. i.e. you can't safely put a reflected list or set into a typed list or dict so it is "banned".

2023-06-08 18:33 UTC, eiis1000 commented
Is there an expected timeline regarding when this will be merged in? Seems there've been no changes in months, and I'm very eager to be rid of that pending deprecation warning :)

2023-12-04 14:44 UTC, closed without merging

2023-12-27 17:51 UTC, dlee992 commented
Hi, what's the status of this PR? Perhaps I can help with it, since I guess many users want to use this new `typed set`.

2024-06-03 14:35 UTC, eiis1000 commented
Seconding the status inquiry, my organization has been waiting for this PR to be merged for well over a year at this point

2024-10-16 19:26 UTC, sklam commented on numba/tests/test_setimpl.py
> +        key_bytes = bytes(key)
If `key` is an `int`, this will just allocate a zero-filled byte string of 3 elements

2024-10-16 19:34 UTC, sklam commented
I wonder if there's a way to make the error message more user friendly when the Set is used with unhashable type.

e.g.

```python
from numba import typed, typeof
import numpy as np


arr = np.arange(10)
a = typed.Set.empty(typeof(arr))
a.add(arr)
```
traceback:

```pytb
Traceback (most recent call last):
  File "/Users/siu/dev/numba/udt.py", line 7, in <module>
    a.add(arr)
  File "/Users/siu/dev/numba/numba/typed/typedset.py", line 144, in add
    return _additem(self, key)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/siu/dev/numba/numba/core/dispatcher.py", line 423, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/siu/dev/numba/numba/core/dispatcher.py", line 364, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
No implementation of function Function(<function impl_set_add at 0x10f3137e0>) found for signature:

 >>> impl_set_add(SetType[array(int64, 1d, C)]<iv=None>, array(int64, 1d, C))

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'impl_set_add': File: numba/typed/setobject.py: Line 538.
    With argument(s): '(SetType[array(int64, 1d, C)]<iv=None>, array(int64, 1d, C))':
   Rejected as the implementation raised a specific error:
     NumbaNotImplementedError: Failed in nopython mode pipeline (step: native lowering)
   Cannot cast none to int64: %".41" = load i8*, i8** %".25"
   During: lowering "status = call $38load_global.5(s, casted_key, $72call.12, func=$38load_global.5, args=[Var(s, setobject.py:545), Var(casted_key, setobject.py:546), Var($72call.12, setobject.py:547)], kws=(), vararg=None, varkwarg=None, target=None)" at /Users/siu/dev/numba/numba/typed/setobject.py (547)
  raised from /Users/siu/dev/numba/numba/core/base.py:704

- Resolution failure for non-literal arguments:
None

During: resolving callee type: BoundFunction((<class 'numba.core.types.containers.SetType'>, 'add') for SetType[array(int64, 1d, C)]<iv=None>)
During: typing of call at /Users/siu/dev/numba/numba/typed/typedset.py (38)


File "numba/typed/typedset.py", line 38:
def _additem(s, key):
    s.add(key)
    ^
```

2025-06-19 14:36 UTC, esc commented
@kc611 since I would like to commence the review soon, can you first `git rebase main` this? I can push to your branch if you want to.

2025-06-19 18:16 UTC, esc commented
@kc611 looks like there might be a few test failures to look into.

2025-06-27 09:17 UTC, esc requested changes
I've reviewed the documentation.

2025-06-27 09:17 UTC, esc commented on docs/source/reference/pysupported.rst
> +As of version 0.58.0, a new implementation of the set data type is available,
```suggestion
As of version 0.62.0, a new implementation of the set data type is available,
```

2025-06-27 09:17 UTC, esc commented on docs/source/reference/pysupported.rst
> +the *typed-set*. This is compiled library backed, type-homogeneous
```suggestion
the *typed-set*. This is a compiled library backed, type-homogeneous
```

2025-06-27 09:17 UTC, esc commented on docs/source/reference/pysupported.rst
> +You will need to import it explicitly from the `numba.typed` module::
```suggestion
You will need to import it explicitly from the ``numba.typed`` module::
```

2025-06-27 09:17 UTC, esc commented on docs/source/reference/pysupported.rst
> +    In [4]: my_set = Set(types.intp)
Question: can the `Set` also be initialized w/o a type and then be specialized with the first `add`?

2025-06-30 11:59 UTC, esc requested changes
There are a few things here to look at, some issues and typos with the documentation.

BUT, as I was reviewing the basic API, I stumbled upon a pretty severe corruption bug, which can be triggered as follows:

```
In [1]: from numba.typed import Set

In [2]: from numba import intp

In [3]: s = Set.empty(intp)

In [4]: s.add(1)

In [5]: [i for i in s]
Out[5]: [1]

In [6]: s.discard(1)
Out[6]: 0

In [7]: [i for i in s]
Out[7]: []

In [8]: s.add(1)

In [9]: [i for i in s]
Out[9]: [0]
```

So it seems related to `discard` since after that I add `1` to the `Set` but when I iterate over it, it turns out it contains `0`? Or it's not printing correctly, I don't know, but this needs looking at.

2025-06-30 11:59 UTC, esc commented on docs/source/reference/pysupported.rst
> +    In [4]: my_set = Set(types.intp)
The answer seems to be no:

```
In [16]: s = Set()

In [17]: s.add(1)
Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
Traceback (most recent call last):
  File "/home/vhaenel/numba/numba/typed/typedset.py", line 112, in _numba_type_
    raise TypeError("invalid operation on untyped set")
TypeError: invalid operation on untyped set
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[17], line 1
----> 1 s.add(1)

File ~/numba/numba/typed/typedset.py:144, in Set.add(self, key)
    143 def add(self, key):
--> 144     return _additem(self, key)

File ~/numba/numba/core/dispatcher.py:687, in _DispatcherBase.typeof_pyval(self, val)
    681 """
    682 Resolve the Numba type of Python value *val*.
    683 This is called from numba._dispatcher as a fallback if the native code
    684 cannot decide the type.
    685 """
    686 try:
--> 687     tp = typeof(val, Purpose.argument)
    688 except (errors.NumbaValueError, ValueError):
    689     tp = types.pyobject

File ~/numba/numba/core/typing/typeof.py:33, in typeof(val, purpose)
     31 # Note the behaviour for Purpose.argument must match _typeof.c.
     32 c = _TypeofContext(purpose)
---> 33 ty = typeof_impl(val, c)
     34 if ty is None:
     35     msg = _termcolor.errmsg(
     36         f"Cannot determine Numba type of {type(val)}")

File ~/miniconda3/envs/numba_3.13/lib/python3.13/functools.py:934, in singledispatch.<locals>.wrapper(*args, **kw)
    931 if not args:
    932     raise TypeError(f'{funcname} requires at least '
    933                     '1 positional argument')
--> 934 return dispatch(args[0].__class__)(*args, **kw)

File ~/numba/numba/core/typing/typeof.py:50, in typeof_impl(val, c)
     47 if tp is not None:
     48     return tp
---> 50 tp = getattr(val, "_numba_type_", None)
     51 if tp is not None:
     52     return tp

File ~/numba/numba/typed/typedset.py:112, in Set._numba_type_(self)
    109 @property
    110 def _numba_type_(self):
    111     if self._set_type is None:
--> 112         raise TypeError("invalid operation on untyped set")
    113     return self._set_type

TypeError: invalid operation on untyped set

```

2025-06-30 11:59 UTC, esc commented on docs/source/reference/pysupported.rst
> +    In [4]: my_set = Set(types.intp)
The `numba.typed.List` will specialize.

2025-06-30 11:59 UTC, esc commented on docs/source/reference/pysupported.rst
> +    In [4]: my_set = Set(types.intp)
```
In [19]: from numba.typed import List

In [20]: l = List()

In [21]: l.append(1)

In [22]: l
Out[22]: ListType[int64]([1])
```

2025-06-30 11:59 UTC, esc commented on docs/source/reference/pysupported.rst
> +    In [4]: my_set = Set(types.intp)
Actually, the whole line is buggy:

```
In [3]: s = Set(intp)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 s = Set(intp)

TypeError: Set.__init__() takes 1 positional argument but 2 were given
```

So does it need to be:


```suggestion
    In [4]: my_set = Set.empty(types.intp)
```

2025-06-30 11:59 UTC, esc commented on docs/upcoming_changes/8741.highlight.rst
> +
I am not sure how to read the stuff below. `set` is a builtin type. And `Set` can't be called directly. Also doesn't `len(s)` lead to `__len__`, so that makes the listing non-uniform how about instead just listing the supported functions:

```
s.__len__()
s.add(i)
s.discard(i)
s.__contains__(i)
s.__iter__()
```

2025-06-30 11:59 UTC, esc commented on docs/upcoming_changes/8741.highlight.rst
> +
Also, having a `__repr__` would be really really nice. Like this I always need to iterate over the set to view it's contents, otherwise we just get the object ID:

```
>>> s
<numba.typed.typedset.Set object at 0x7fcb8e88c1a0>
```

2025-07-01 12:51 UTC, esc commented on numba/core/types/containers.py
> +        )
I don't understand this code, why would you write this like this? Can you not just:

```
return not isinstance(self.key_type, Undefined)
```

I don't understand the need to wrap this in a singleton tuple and then in `any`?

2025-07-01 12:56 UTC, esc commented on numba/core/types/containers.py
> +        return res
I don't understand under what circumstances this code can be executed. From what I understand on-the-fly refinement of a `Set` is not possible:

```
In [18]: s = Set()

In [19]: s.add(1)
Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/typed/typedset.py", line 112, in _numba_type_
    raise TypeError("invalid operation on untyped set")
TypeError: invalid operation on untyped set
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[19], line 1
----> 1 s.add(1)

File ~/git/numba/numba/typed/typedset.py:144, in Set.add(self, key)
    143 def add(self, key):
--> 144     return _additem(self, key)

File ~/git/numba/numba/core/dispatcher.py:687, in _DispatcherBase.typeof_pyval(self, val)
    681 """
    682 Resolve the Numba type of Python value *val*.
    683 This is called from numba._dispatcher as a fallback if the native code
    684 cannot decide the type.
    685 """
    686 try:
--> 687     tp = typeof(val, Purpose.argument)
    688 except (errors.NumbaValueError, ValueError):
    689     tp = types.pyobject

File ~/git/numba/numba/core/typing/typeof.py:33, in typeof(val, purpose)
     31 # Note the behaviour for Purpose.argument must match _typeof.c.
     32 c = _TypeofContext(purpose)
---> 33 ty = typeof_impl(val, c)
     34 if ty is None:
     35     msg = _termcolor.errmsg(
     36         f"Cannot determine Numba type of {type(val)}")

File ~/miniconda3-arm64/envs/numba_3.13_02/lib/python3.13/functools.py:934, in singledispatch.<locals>.wrapper(*args, **kw)
    931 if not args:
    932     raise TypeError(f'{funcname} requires at least '
    933                     '1 positional argument')
--> 934 return dispatch(args[0].__class__)(*args, **kw)

File ~/git/numba/numba/core/typing/typeof.py:50, in typeof_impl(val, c)
     47 if tp is not None:
     48     return tp
---> 50 tp = getattr(val, "_numba_type_", None)
     51 if tp is not None:
     52     return tp

File ~/git/numba/numba/typed/typedset.py:112, in Set._numba_type_(self)
    109 @property
    110 def _numba_type_(self):
    111     if self._set_type is None:
--> 112         raise TypeError("invalid operation on untyped set")
    113     return self._set_type

TypeError: invalid operation on untyped set
```

2025-07-01 12:59 UTC, esc commented on numba/core/types/containers.py
> +        InitialValue.__init__(self, initial_value)
This whole section looks like it was copied from the code for the reflected list and not the typed list.

Reflected list: https://github.com/numba/numba/blob/main/numba/core/types/containers.py#L422-L429

Typed list: https://github.com/numba/numba/blob/main/numba/core/types/containers.py#L622-L638

As you can see one has the whole `iv` construct but the other doesn't

2025-07-01 13:00 UTC, esc commented on numba/core/types/containers.py
> +        return self.key_type, str(self.initial_value)
If there is no initial value, then we don't need to return that.

2025-07-01 13:03 UTC, esc commented on numba/core/types/containers.py
> +        InitialValue.__init__(self, initial_value)
I looked again, seems like the typed Dict does have an `iv` section. I am not sure that is correct either.

2026-04-03 01:49 UTC, swap357 commented
closing this as typedSet implementation was merged with https://github.com/numba/numba/pull/10131