Refactored Numpy documentation to follow numpy user reference
numba/numba pull request #8779
Opened 2023-02-23 18:30 UTC by kc611

This PR is first of a series of PRs aimed towards improving Numba's documentation of it's NumPy support capabilities. 

It makes the current Numba documentation for NumPy support to follow the format of NumPy User Reference Guide (http://www.numpy.org/1.23/reference/index.html)

Note to reviewer: This PR doesn't change the existing contents by a significant degree and is more concerned with rearrangement of existing contents into proper sections. The actual content changes will be made section-by-section in following PRs to keep it easier for review.

2023-05-05 10:56 UTC, esc commented
@kc611 -- it seems like there is now a conflict with `main`. Since this PR has not been reviewed yet, I would recommend to rebase this onto `main`.

2023-08-04 09:44 UTC, esc commented
Seems like there is an RST failure:

```
/home/vsts/work/1/s/docs/source/reference/numpysupported.rst:970:Duplicate explicit target name: "numpy-random".
```

2026-01-06 17:17 UTC, esc commented
ping @kc611 can we rebase and update this? Or is it too old?

2026-05-11 13:08 UTC, esc commented
@kc611 can you rebase this on `main` to resolve the conflicts?

2026-05-19 09:02 UTC, esc commented
@kc611 thank you for rebasing this. There is now an error during sphinx build on Azure:

```
/home/vsts/work/1/s/docs/source/reference/numpysupported.rst:1030:Duplicate explicit target name: "numpy-random".
```

2026-05-20 13:59 UTC, kc611 commented
@esc I think its now ready for review.

2026-08-04 12:33 UTC, esc requested changes
I have given this a closer look today and managed to identify some issues regarding the documented functions.

2026-08-04 12:33 UTC, esc commented on docs/source/reference/numpysupported.rst
> +* :func:`numpy.intersect1d` (only 3 first arguments: ar1, ar2, and assume_unique)
```suggestion
* :func:`numpy.intersect1d` (only 3 first arguments: ``ar1``, ``ar2``, and ``assume_unique``)
```

2026-08-04 12:33 UTC, esc commented on docs/source/reference/numpysupported.rst
> -* :meth:`~numpy.ndarray.tobytes` (without arguments)
the `tobytes` method documentation seems to have gone missing?

2026-08-04 12:33 UTC, esc commented on docs/source/reference/numpysupported.rst
> +* :func:`numpy.nan_to_num` (only the 3 first arguments)
I do not believe that the limitation introduced here about the arguments is correct. This limitation is not present on the variant of this file on `main`.

```suggestion
* :func:`numpy.nan_to_num`
```

The following reproducer shows that args 4 and 5 are accepted and do appear to work as intended:

```python
import numpy as np
from numba import njit

@njit
def nan_to_num_all_args(x):
    # posinf/neginf are the 4th/5th args -- doc claims only the first 3 work
    return np.nan_to_num(x, copy=True, nan=-1.0, posinf=999.0, neginf=-999.0)

x = np.array([1.0, np.nan, np.inf, -np.inf, 5.0])
print(nan_to_num_all_args(x))
# [   1.   -1.  999. -999.    5.]
```

2026-08-04 18:04 UTC, kc611 commented on docs/source/reference/numpysupported.rst
> -* :meth:`~numpy.ndarray.tobytes` (without arguments)
Added this in [0467f04](https://github.com/numba/numba/pull/8779/commits/0467f048ccc6f6cb36e1e8be6178d017331b6d70)

2026-08-05 08:36 UTC, esc requested changes
I re-reviewed this, and found two classes of errors:

a) Two things appear to be misplaced, `tobytes` and `sliding_window_view`
b) The NumPy documentation uses sentence capitalization throughout, most of this doc does to, but I found 7 exceptions to this rule that need to be modified.

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
> +* :meth:`~numpy.ndarray.tobytes` (without arguments)
I believe this is in the wrong place. These are the attributes related to `Memory Layout`. Perhaps place this in the `Array conversion` section below.

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
> +Memory Layout:
```suggestion
Memory layout:
```

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
> +Other Attributes:
```suggestion
Other attributes:
```

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
> +Datetime Support Functions
```suggestion
Datetime support functions
```

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
>  Generator Objects
```suggestion
Generator objects
```

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
>  RandomState and legacy Random number generation
```suggestion
RandomState and legacy random number generation
```

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
> +Iterating Over Arrays
```suggestion
Iterating over arrays
```

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
> +number
```suggestion
Number
```

2026-08-05 08:36 UTC, esc commented on docs/source/reference/numpysupported.rst
> +* :func:`~numpy.lib.stride_tricks.sliding_window_view` (the *subok* argument is
This is misplaced in the `ufunc` section. This should be places below `as_strided` in the section `Indexing Routines`.

2026-08-21 05:28 UTC, esc requested changes
I have found a subtle duplication issue, labelled as instance 1 and instance 2 below. The text is completely duplicated. Also, with `docutils` this gives a duplication error:

```
(numba314) esc@machine~/numba$ docutils --report=1 --halt=5  docs/source/reference/numpysupported.rst /dev/null 2>&1 | grep -i duplicate
docs/source/reference/numpysupported.rst:289: (INFO/1) Duplicate name "numpy arrays" for external target "http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html".
```

2026-08-21 05:28 UTC, esc commented on docs/source/reference/numpysupported.rst
> +`NumPy arrays <http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html>`_
Instance 1

2026-08-21 05:28 UTC, esc commented on docs/source/reference/numpysupported.rst
>  `NumPy arrays <http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html>`_
Instance 2

2026-08-24 12:23 UTC, esc requested changes
Some issues here around placement of scalars section.

2026-08-24 12:23 UTC, esc commented on docs/source/reference/numpysupported.rst
> +Built-in scalar types
This and the sections below appear misplaced. I believe this section and the ones below:

* Numer
* Integer Types (signed)
* Integer Types (unsigned)
* Inexact types

I think they need to be moved to and merged with the section on Scalars above?

NumPy itself has this structure here:

https://numpy.org/doc/stable/reference/arrays.scalars.html

I understand that the repetition here may be needed, but it seems out-of-place, compared to the Scalars section, which has a different kind of list of the scalar types. 

Maybe clean this up so that it's more cohesive?

2026-08-24 12:34 UTC, esc requested changes
I found another misplaced section.

2026-08-24 12:34 UTC, esc commented on docs/source/reference/numpysupported.rst
> +Indexing routines
I believe this section is misplaced. This is currently in the section about:

`Array Types`

But there is also a section:

`Array Routines`

that would be a much better fit for this.

In fact in the NumPy docs, this is exactly where `Indexing Routines` is located:

https://numpy.org/doc/stable/reference/routines.indexing.html

2026-08-25 08:00 UTC, kc611 commented on docs/source/reference/numpysupported.rst
> +Indexing routines
Fixed in [8c2f02b](https://github.com/numba/numba/pull/8779/commits/8c2f02b584b540643344bbf6d1f0b26a1d001b66)

2026-08-25 08:01 UTC, kc611 commented on docs/source/reference/numpysupported.rst
> +Built-in scalar types
Fixed in [8c2f02b](https://github.com/numba/numba/pull/8779/commits/8c2f02b584b540643344bbf6d1f0b26a1d001b66)

2026-08-27 09:24 UTC, esc requested changes
I found some indentation issues here. All other continuation of bullets in the document use 2 spaces for indentation, but these two use three. Simple fix.

2026-08-27 09:24 UTC, esc commented on docs/source/reference/numpysupported.rst
> +   values ``'quicksort'`` and ``'mergesort'``)
```suggestion
  values ``'quicksort'`` and ``'mergesort'``)
```

2026-08-27 09:24 UTC, esc commented on docs/source/reference/numpysupported.rst
> +   arguments.)
```suggestion
  arguments.)
```

2026-08-27 11:10 UTC, esc requested changes
Please restore these two sentences, they were lost in the refactor.

2026-08-27 11:10 UTC, esc commented on docs/source/reference/numpysupported.rst
> +
```suggestion

The corresponding top-level NumPy functions (such as :func:`numpy.prod`)
are similarly supported.

```

This sentence needs to be restored.

2026-08-27 11:10 UTC, esc commented on docs/source/reference/numpysupported.rst
> +
```suggestion

Where applicable, the corresponding top-level NumPy functions (such as
:func:`numpy.argsort`) are similarly supported.

```

2026-08-27 13:44 UTC, esc approved these changes
LGTM!

2026-08-27 13:53 UTC, merged