Updated mk_alloc to support Numba-Dpex compute follows data.
numba/numba pull request #8854
Opened 2023-03-28 17:50 UTC by mingjie-intel

Change is made in mk_alloc to support Numba-Dpex compute follows data. There will be no affect to Numba main function.

2023-03-28 18:08 UTC, DrTodd13 requested changes
Please add this __allocate__ support in the appropriate place in the Numba developer documentation.

2023-03-28 23:01 UTC, diptorupd commented
Some more motivating context behind these changes. The `mk_alloc` function is used inside the Numba parfor machinery to create a new empty NumPy array (by calling numpy.empty) whenever a temporary array is needed to allocate the left-hand-side sub-expression of a parfor node.

In our work on using parfors to support other NumPy-like libraries we want to change the actual library call used to allocate the empty array. These changes extend the `mk_alloc` function to first look if the array type provides an `__allocate__` function and use that instead of the default logic in the original function.

@DrTodd13 can you point me to the file where the documentation should be updated?

2023-03-28 23:25 UTC, DrTodd13 commented
@diptorupd @sklam @stuartarchibald I don't know if the documentation belongs in numba/docs/source/extending or numba/docs/source/developer.  Unbelievably, we don't have a ParallelAccelerator page in the developer docs which was my first idea.  I'm soliciting ideas from Siu and Stuart as to where this should be documented.

2023-04-13 15:54 UTC, sklam commented
/azp run

2023-04-13 15:58 UTC, sklam commented
> @diptorupd @sklam @stuartarchibald I don't know if the documentation belongs in numba/docs/source/extending or numba/docs/source/developer. Unbelievably, we don't have a ParallelAccelerator page in the developer docs which was my first idea. I'm soliciting ideas from Siu and Stuart as to where this should be documented.

I think this is ParallelAccelerator specific enough to have its own page. I think we can add that ParallelAccelerator page in a different PR.

2023-05-02 21:43 UTC, merged