Jupyter magic command for displaying LLVM
numba/numba pull request #8962
Opened 2023-05-15 22:03 UTC by Matt711

As a part of #8960, I'd like to add a Jupyter magic command that displays the LLVM of the jupyter cell. This PR implements the first magic command `%%numba --annotate`. It works by writing the text to of the Jupyter cell to an IPython cache directory, importing, and then passing the "jitted" function to a `numba.core.annotations.Annotate` object which is returned.

2023-05-15 22:08 UTC, Matt711 commented
![image](https://github.com/numba/numba/assets/41342305/c1314f82-c922-4e2b-bb48-16085c31e42b)

2023-05-17 12:10 UTC, gmarkall reviewed
Thanks for sharing progress with this! I made some initial high level comments on the PR. I need also to learn / think a bit more about magics - my main concern is over the robustness of writing out a temp file to annotate (whether we will have trouble capturing all that's required) but we can discuss / explore this a bit more outside this PR before another round of review.

2023-05-17 12:10 UTC, gmarkall commented on numba/__init__.py
> +def load_ipython_extension(ip):
Is this to support `%load_ext numba`? If so, could you add a comment mentioning this, for the benefit of readers unfamiliar with how magics work? (They are new to me, and I imagine others might also benefit from the explanation)

2023-05-17 14:05 UTC, Matt711 commented on numba/core/annotations/IpythonMagic.py
> +@magics_class
I'm not sure we need to handle anything as the default error is clear. You should get a error like below if you use cell magic as line magic.
```
In [3]: %numba --annotate
UsageError: Line magic function `%numba` not found (But cell magic `%%numba` exists, did you mean that instead?).
```

2023-05-23 20:51 UTC, gmarkall commented
**Note to self:** The next step reviewing here is to assess how safe the approach of writing out a temporary source file is; whether there are cases in which it could break, or if there's a way to get at the source code without writing to disk. One thing to look at for inspiration might be the Jupyter cache locator, to see how that handles code in cells of notebooks.

@stuartarchibald / @siu do you have any thoughts / suggestions off the top of your head about getting access to the source of functions in notebook cells?

2023-07-06 08:28 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +            member[1] for member in members if hasattr(member[1], "py_func")
I think the canonical way to check whether a function is jitted would be to see if it's an instance of `numba.core.dispatcher.Dispatcher`.

2023-07-06 08:39 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +    def _preprocess_cell(self, cell):
Having a function just to strip the cell seems a bit heavyweight - perhaps this could just be rolled into the `_build_module_spec()` function.

2023-07-06 08:39 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +
From suggestion above that this may not be needed:

```suggestion
```

2023-07-06 08:42 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +            os.makedirs(lib_dir)
Do we need to do something to gracefully handle the case where creating the directory fails?

2023-07-06 08:43 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +            f.write(code)
What if opening the file fails? E.g. if the `lib_dir` is a file that already exists - do we need to handle that gracefully too?

2023-07-06 08:49 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +            spec.loader.exec_module(numba_module)
This seems to execute the module in its own namespace - What happens if it refers to globals in the notebook that aren't defined in the module?

2023-07-06 08:52 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +            keys = [k for k in mdict if not k.startswith('_')]
Similarly, isn't this presenting anything with an underscore prefix being added to the namespace of the notebook? Do we want to prevent that?

2023-07-06 08:59 UTC, gmarkall requested changes
I've taken another look at this. My present thinking is that writing to a temp file so that the source can be found is an OK approach - I can't see any serious robustness issues with it, with the caveat this is outside my area of experience / expertise.

However, I think the way in which we execute the imported module in its own namespace seems likely to cause issues. I think the general expectation is that code in the cell runs in the same namespace as the rest of the notebook, so isolating its namespace might stop it accessing globals from elsewhere in the notebook, and also make it hard to ensure everything from its namespace gets into the notebook's namespace. (Again with the caveat that this is my understanding, but I'm not an expert here 🙂 )

2023-07-06 12:20 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +            ann = Annotate(numba_functions[0])
Noted during discussion that this produces an annotation for only the first jitted function.

2023-07-06 12:21 UTC, gmarkall commented on numba/core/annotations/ipython_magic.py
> +            ann = Annotate(numba_functions[0])
(Due to potential corruption of output when displaying a lot in the notebook)

2023-07-06 12:25 UTC, gmarkall commented on numba/tests/test_ipython_magic.py
> +def f(x):
Note from discussion: we should also add a test where something defined outside the cell is referred to.

2023-07-31 12:58 UTC, closed without merging