fix missing nopython keyword in cuda random module
numba/numba pull request #8964
Opened 2023-05-16 12:59 UTC by esc

Fixes: #8951

2023-05-17 14:52 UTC, gmarkall commented
gpuci run tests

2023-05-17 14:58 UTC, gmarkall requested changes
The code changes look good to me in their present form (assuming gpuCI passes) - just a couple of comments on the explanatory comments.

2023-05-17 14:58 UTC, gmarkall commented on numba/cuda/random.py
> +# @jit-decorated functions. This required the a fallback to object mode. With
"the a" - should this be:
```suggestion
# @jit-decorated functions. This required fallback to object mode. With
```

2023-05-17 14:58 UTC, gmarkall commented on numba/cuda/random.py
> +# Numba 0.59.0 this fallback must be explicitly enabled.
I think there is no fallback in the future:

```suggestion
# Numba 0.59.0 object mode must be explicitly enabled.
```

2023-05-18 05:50 UTC, esc commented
@gmarkall thank you for the review, I have addressed the review comments accordingly and pushed two new commits.

2023-05-18 09:06 UTC, gmarkall commented
gpuci run tests

2023-05-18 09:42 UTC, gmarkall approved these changes
Many thanks for the fix - this looks good to me!

2023-05-18 20:04 UTC, merged