Adding np.geomspace
numba/numba pull request #9068
Opened 2023-07-11 05:50 UTC by KrisMinchev

Adding implementation of np.geomspace to Numba. Currently it only supports scalar inputs, both real and complex.

2023-07-11 07:24 UTC, esc commented
@KrisMinchev thank you for submitting this. I have labeled it as "Ready for Review". I have taken a glance already though, and I can comment that this will need: a) fixing flake8 issues and b) adding tests. Also, to set some expectations: the Numba backlog is quite full so it may be some time until a reviewer will be able to pick this up. Hence I have placed it in the PR backlog milestone for now.

2023-07-12 19:01 UTC, guilhermeleobas requested changes
Hi @KrisMinchev, thanks a lot for working on this feature. Congrats on submitting your first Numba PR.

I have a few changes and found a test case that fails with your implementation. Also, could you update `numpysupported.rst` file and include `numpy.geomspace`?

2023-07-12 19:01 UTC, guilhermeleobas commented on numba/tests/test_np_functions.py
> +                                       rtol=1.05e-07)
Use `self.assertPreciseEqual` instead of `np.testing.assert_allclose`.

2023-07-12 19:01 UTC, guilhermeleobas commented on numba/tests/test_np_functions.py
> +            np.testing.assert_allclose(pyfunc(start, stop, num),
Use `self.assertPreciseEqual` instead of `np.testing.assert_allclose`.

2023-07-13 06:44 UTC, KrisMinchev commented on numba/np/arrayobj.py
> +        def impl(start, stop, num=50):
The current Numba implementation of `np.logspace` does not support the dtype parameter. Expanding the `np.logspace` overload might solve this issue. We can alternatively use `np.result_type` to deduce the type, but I am not sure if that won't hurt the performance of the implementation.

2023-07-13 06:55 UTC, KrisMinchev commented on numba/tests/test_np_functions.py
> +                      str(raises.exception))
I might expand the test cases of `test_geomspace3_with_num_basic` to actually use 3 parameters and keep this function as it is right now.

2023-07-13 07:15 UTC, KrisMinchev commented on numba/tests/test_np_functions.py
> +                      str(raises.exception))
I also see that `test_geomspace3_basic` is covering similar cases to `test_geomspace2_basic`, so I might remove the former.

2023-07-13 08:18 UTC, esc commented
@guilhermeleobas thank you for reviewing this. Do you think this has a chance to make it into 0.58? To be tagged the week starting 07th August?

2023-07-13 18:21 UTC, guilhermeleobas commented
> @guilhermeleobas thank you for reviewing this. Do you think this has a chance to make it into 0.58? To be tagged the week starting 07th August?

Yes, I think it can.

2023-07-13 18:36 UTC, guilhermeleobas commented on numba/np/arrayobj.py
> +        def impl(start, stop, num=50):
Ok, this can be done in a follow-up PR.

2023-07-13 19:35 UTC, guilhermeleobas requested changes
Thanks for addressing the remaining issues, @KrisMinchev. I have a few more comments to make, which may solve the precision issue you're having.

2023-07-13 19:35 UTC, guilhermeleobas commented on numba/np/arrayobj.py
> +            stop = np.complex64(stop)
This is truncating start and stop to `complex64`. In my system, the default type for complex values is `np.complex128` and the following inputs gives different results:

```
from numba import njit
import numpy as np

@njit
def foo(start, stop, num):
    return np.geomspace(start, stop, num=num)

start = 1j
stop = np.complex64(16j)
num = 3
print(foo(start, stop, num))
print(np.geomspace(start, stop, num=num))

# [0. +1.j         0. +4.00000026j 0.+16.j        ]
# [0. +1.j 0. +4.j 0.+16.j]
```

At compile time you can determine the resulting dtype (use `np.promote_types` for that) and use cast start/stop using this resulting dtype. Code should look something like this:

```python
    if any(isinstance(arg, types.Complex) for arg in [start, stop]):
        from numba.np.numpy_support import as_dtype, from_dtype
        result_dtype = from_dtype(np.promote_types(as_dtype(start), as_dtype(stop)))
        def impl(start, stop, num=50):
            ...
            start = result_dtype(start)
            stop = result_dtype(stop)
            ...
```

2023-07-14 05:43 UTC, esc commented
> > @guilhermeleobas thank you for reviewing this. Do you think this has a chance to make it into 0.58? To be tagged the week starting 07th August?
> 
> Yes, I think it can.

OK, splendid, I have updated the milestone accordingly!

2023-07-17 16:53 UTC, guilhermeleobas requested changes
Hi @KrisMinchev, thanks for the update. I only have one last change request.

2023-07-17 16:53 UTC, guilhermeleobas commented on numba/tests/test_np_functions.py
> +        self.assertPreciseEqual(y, pfunc3(-100, -1, num=3), abs_tol=1e-7)
Some `abs_tol` are redundant and can be removed, others you can decrease its value.

2023-07-19 08:04 UTC, esc commented
@guilhermeleobas is this ready to merge now?

2023-07-19 13:31 UTC, guilhermeleobas commented
@esc, yes!

2023-07-24 21:23 UTC, merged