Add np.vsplit and np.hsplit
numba/numba pull request #9082
Opened 2023-07-18 10:01 UTC by KrisMinchev

Adding implementations of `np.vsplit` and `np.hsplit` to Numba, as requested in issue https://github.com/numba/numba/issues/4074. Note that these are special cases of the `np.split` function.

2023-07-24 16:20 UTC, guilhermeleobas requested changes
Hi @KrisMinchev, thanks for working on this. I've found a case where your code fails: NumPy docs says the second argument to `vsplit`/`hsplit` must be an integer or 1D-array, but any iterable is accepted.

2023-07-24 16:20 UTC, guilhermeleobas commented on numba/np/arrayobj.py
> +        raise errors.TypingError(msg)
Although NumPy says the second argument is an array, the following is also valid:

```python
import numpy as np
from numba import njit

@njit
def foo(a):
    return np.hsplit(a, [3, 6])

x = np.arange(16).reshape(4, 4)
# print(foo(x))
print(foo.py_func(x))
```

2023-07-27 15:43 UTC, guilhermeleobas requested changes
One last thing and it should be good to merge

2023-07-27 15:43 UTC, guilhermeleobas commented on numba/np/arrayobj.py
> +               'must be an integer, an array, a list, or a tuple')
```suggestion
        msg = ('The argument "indices_or_sections" must be int or 1d-array')
```

2023-07-27 15:43 UTC, guilhermeleobas commented on numba/np/arrayobj.py
> +               'must be an integer, an array, a list, or a tuple')
```suggestion
        msg = ('The argument "indices_or_sections" must be int or 1d-array')
```

2023-07-27 15:43 UTC, guilhermeleobas commented on numba/np/arrayobj.py
> +               'must be an integer, an array, a list, or a tuple')
```suggestion
        msg = ('The argument "indices_or_sections" must be int or 1d-array')
```

2023-07-27 15:43 UTC, guilhermeleobas commented on numba/tests/test_np_functions.py
> +
Are these tests from the NumPy test suite? If yes, add a link referencing the NumPy GitHub repo

2023-07-28 14:16 UTC, guilhermeleobas requested changes
Hi @KrisMinchev, thanks again. I have a few more request changes and PR should be good to merge

2023-07-31 10:09 UTC, KrisMinchev commented on numba/tests/test_np_functions.py
> +    def test_vsplit_exception(self):
```suggestion
    def test_vhdsplit_exception(self):
        # Single test method for vsplit, hsplit and dsplit
        for (f, mindim, name) in [(vsplit, 2, "vsplit"),
                                  (hsplit, 1, "hsplit"),
                                  (dsplit, 3, "dsplit")]:
            cfunc = jit(nopython=True)(f)

            self.disable_leak_check()

            with self.assertRaises(TypingError) as raises:
                cfunc(1, 2)
            self.assertIn('The argument "ary" must be an array',
                        str(raises.exception))

            with self.assertRaises(TypingError) as raises:
                cfunc("abc", 2)
            self.assertIn('The argument "ary" must be an array',
                        str(raises.exception))

            with self.assertRaises(TypingError) as raises:
                cfunc(np.array([[1, 2, 3, 4], [1, 2, 3, 4]]), "abc")
            self.assertIn(('The argument "indices_or_sections" must be int or '
                        '1d-array'),
                        str(raises.exception))

            with self.assertRaises(ValueError) as raises:
                cfunc(np.array(1), 2)
            self.assertIn(name + ' only works on arrays of ' + str(mindim) +
                          ' or more dimensions',
                        str(raises.exception))
```

2023-07-31 17:18 UTC, guilhermeleobas commented on numba/tests/test_np_functions.py
> +    def test_vsplit_exception(self):
Great! That should be enough

2023-08-01 07:39 UTC, KrisMinchev commented
Hi @guilhermeleobas, thank you for your requests. I have addressed them in my last commits.

2023-08-02 17:17 UTC, guilhermeleobas requested changes

2023-08-02 17:17 UTC, guilhermeleobas commented on numba/tests/test_np_functions.py
> +            yield np.arange(8.0).reshape(2, 2, 2), 2
Tests from hsplit/vsplit/dsplit are the same. Merge the functions into a single one

2023-08-02 17:17 UTC, guilhermeleobas commented on numba/tests/test_np_functions.py
> +            # test_shape_base.py#L553-L564
Keep the URL in a single line

2023-08-02 17:17 UTC, guilhermeleobas commented on numba/tests/test_np_functions.py
> +            # test_shape_base.py#L616-L624
Keep the URL in a single line

2023-08-03 09:55 UTC, gmarkall commented
(Note: the build fail is just a flake8 issue)

2023-08-07 18:58 UTC, guilhermeleobas approved these changes
Thanks @KrisMinchev

2023-08-15 16:05 UTC, merged