Add tests for np.row_stack
numba/numba pull request #9085
Opened 2023-07-24 11:55 UTC by KrisMinchev

Since `np.row_stack` is an alias for `np.vstack`, there is no need for a separate Numba impementation for it. This PR adds a test for `np.row_stack` for every test for `np.vstack`.

2023-07-24 16:39 UTC, guilhermeleobas requested changes
Hi @KrisMinchev, I have only some minor changes. But PR looks great. Thanks

2023-07-24 16:39 UTC, guilhermeleobas commented on numba/tests/test_dyn_array.py
> +    return np.row_stack((a,b,c))
```suggestion
def np_row_stack(a, b, c):
    return np.row_stack((a, b, c))
```

2023-07-24 16:39 UTC, guilhermeleobas commented on numba/tests/test_dyn_array.py
> +        cfunc_rowstack = nrtjit(pyfunc_rowstack)
Create a for loop instead:

```suggestion
        for pyfunc in (np_vstack, np_row_stack):
            cfunc = nrtjit(pyfunc)
            ...
```

2023-07-26 14:10 UTC, stuartarchibald reviewed
Thanks for the patch, couple of minor comments else looks good.

2023-07-26 14:10 UTC, stuartarchibald commented on docs/upcoming_changes/9085.np_support.rst
> +This PR improves on `#4074 <https://github.com/numba/numba/issues/4074>` by adding support for np.row_stack().
```suggestion
Support is added for ``numpy.row_stack()``.
```

2023-07-26 14:10 UTC, stuartarchibald commented on docs/upcoming_changes/9085.np_support.rst
> +=============================================
```suggestion
==========================================
```
think this line is too long?

2023-07-26 16:09 UTC, KrisMinchev commented
> Thanks for the patch, couple of minor comments else looks good.

Hi @stuartarchibald, thank you for the comments. I have updated the towncrier accordingly.

2023-07-26 20:53 UTC, guilhermeleobas approved these changes
Approved! Thanks, @KrisMinchev

CI failure is not related to this PR!

2023-07-27 21:49 UTC, merged