Fixed towncrier template rendering
numba/numba pull request #9117
Opened 2023-08-03 10:40 UTC by kc611

Resolves #9102,

As per the issue, 
Adds a template for towncrier's auto-release notes generation and fixes towncrier build rendering issues.

2023-08-04 06:19 UTC, gmarkall commented
Moved into the 0.58RC milestone as it fixes #9102 which is in it.

2023-08-04 14:16 UTC, sklam requested changes
Thanks for the patch. I noticed a few things that need changing:

- heading level is not aligning with previous CHANGE_LOG entries
- the issue link not going to numba repo
- the section ordering can be improved

2023-08-04 14:16 UTC, sklam commented on docs/upcoming_changes/template.rst
> +{% for category, val in definitions.items() if category in sections[section] %}
We should change the ordering of the sections. Currently, the CUDA session is going before the new_features. I found this the ordering is driven by the sections ordering in towncrier.toml. I suggest the following changes to it:

```

[[tool.towncrier.type]]
    directory = "highlight"
    name = "Highlights"
    showcontent = true

[[tool.towncrier.type]]
    directory = "new_feature"
    name = "New Features"
    showcontent = true

[[tool.towncrier.type]]
    directory = "improvement"
    name = "Improvements"
    showcontent = true

[[tool.towncrier.type]]
    directory = "np_support"
    name = "NumPy Support"
    showcontent = true

[[tool.towncrier.type]]
    directory = "cuda"
    name = "CUDA API Changes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "performance"
    name = "Performance Improvements and Changes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "bug_fix"
    name = "Bug Fixes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "change"
    name = "Changes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "deprecation"
    name = "Deprecations"
    showcontent = true

[[tool.towncrier.type]]
    directory = "expired"
    name = "Expired Deprecations"
    showcontent = true

[[tool.towncrier.type]]
    directory = "compatibility"
    name = "Compatibility Notes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "doc"
    name = "Documentation Changes"
    showcontent = true

[[tool.towncrier.type]]
    directory = "infrastructure"
    name = "Infrastructure Related Changes"
    showcontent = true
```

2023-08-16 08:56 UTC, esc requested changes
for a search and replace mistake

2023-08-16 09:03 UTC, esc requested changes
fixup missing `=`

2023-08-16 09:03 UTC, esc commented on docs/upcoming_changes/9095.bug_fix.rst
> +Support `dtype` keyword argument in `numpy.arange` with `parallel"True`
```suggestion
Support `dtype` keyword argument in `numpy.arange` with `parallel=True`
```

2023-08-16 09:18 UTC, esc commented
Testing via #9135 yields:

<img width="307" alt="Screen Shot 2023-08-16 at 11 17 57" src="https://github.com/numba/numba/assets/41563/4405dd32-f3e7-4ff6-9a14-6240e4efbfc0">

2023-08-16 09:24 UTC, esc approved these changes
I have verified via #9135 that the new headings look good and the `towncrier build --draft` output can be used to partially auto-generate the new Numba change log.

2023-08-16 10:03 UTC, merged