Add support for np.resize()
numba/numba pull request #9118
Opened 2023-08-03 12:32 UTC by KrisMinchev

This PR improves on #4074 by implementing the function `np.resize()`.

2023-08-09 14:51 UTC, guilhermeleobas requested changes
Thanks for the addition, @KrisMinchev. I only have one request change.

2023-08-09 14:51 UTC, guilhermeleobas commented on numba/np/arrayobj.py
> +    if isinstance(new_shape, types.Integer):
You can actually unify both implementations and move the isinstance check to inside `impl`:

```python
def impl(a, new_shape):
    ...
    if isinstance(new_shape, tuple):
        new_size = 1
        for dim_length in np.asarray(new_shape):
            new_size *= dim_length
            if dim_length < 0:
                msg = 'All elements of `new_shape` must be non-negative'
                raise ValueError(msg)
    else:
        if new_shape < 0:
            msg2 = 'All elements of `new_shape` must be non-negative'
            raise ValueError(msg2)
        new_size = new_shape

    if a.size == 0:
        return np.zeros(new_shape).astype(a.dtype)

    ....
```

The `isinstance` check will be eliminated at compile time and only the branch that is true is kept.

2023-08-11 07:55 UTC, KrisMinchev commented
Hi @guilhermeleobas, thank you for the review. I have merged the implementations and moved the `isinstance` check.

2023-08-11 15:14 UTC, guilhermeleobas approved these changes
LGTM. Thanks, @KrisMinchev.

2023-08-15 16:04 UTC, merged

2023-08-15 16:05 UTC, esc commented
@KrisMinchev thank you for the patch!

2025-06-06 13:56 UTC, mtsokol commented
Hi @guilhermeleobas, is `np.resize()` missing from the "supported NumPy functions" section? I.e. Will `@njit` work with `np.resize`?

https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html#functions

2025-06-06 14:41 UTC, guilhermeleobas commented
Hi @mtsokol, it seems that `np.resize()` is missing from the "supported NumPy functions" section. But it should work just fine in Numba.

2025-06-06 17:26 UTC, esc commented
@mtsokol pull-requests to update the documentation welcome, if anything is amiss ❤️