Remove Python 3.8 support.
numba/numba pull request #9310
Opened 2023-11-29 11:37 UTC by stuartarchibald

This PR removes support for Python 3.8, effectively making Numba's new minimum supported Python version 3.9. Commits can be reviewed individually if preferred. This also fixes a bug in error handling in `numba.tests.support.print_azure_matrix` and augments that function with a print out of the "reverse" map such that the Azure information is available grouped by Python and also by NumPy version.

2023-11-29 13:01 UTC, kc611 requested changes
I have given the PR a look, current changes largely look good without any major issues/changes. There are a few instance still for 3.8 specific code that remain which the PR may have missed:

https://github.com/numba/numba/blob/51fce0235e8b7ba1dc9ae41657c546a608b02847/numba/core/transforms.py#L114

https://github.com/numba/numba/blob/51fce0235e8b7ba1dc9ae41657c546a608b02847/numba/core/transforms.py#L188

And a few questions I've highlighted below

2023-11-29 13:13 UTC, stuartarchibald commented on azure-pipelines.yml
> -        PYTHON: '3.11'
Historically, the aim of the Azure config has been to test a broad range of configurations and also the extreme ends of the support matrix, i.e. oldest supported [Python, NumPy] crossed with newest supported [Python, NumPy]. This condition was broken as part of the 3.12 update and this patch is rectifying it. In the case of Windows/OSX, the build machines are slower and so only a couple of configurations are run, which are oldest supported and newest supported. Hope this helps explain the changes?

2023-11-29 13:14 UTC, stuartarchibald commented on numba/tests/test_builtins.py
> +        # In Python 3.8+ "start" can be specified as a kwarg, so test that too
I elected to leave this in as a reference for when this kwarg first appeared. Am also ok to remove it if you feel otherwise?

2023-11-29 13:17 UTC, stuartarchibald commented on azure-pipelines.yml
> -        TEST_START_INDEX: 9
Yes, it's just a move of the job in which they are running. The Azure change in general were to try and increase the spread of things covered, make sure that the threading layer tests were all running exactly the same configuration and also reduce the number of jobs to run. Running `numba.tests.support.print_azure_matrix()`  will show what the configuration looks like in a more readable form which might help when looking at this change.

2023-11-29 13:25 UTC, stuartarchibald commented
> I have given the PR a look, current changes largely look good without any major issues/changes. There are a few instance still for 3.8 specific code that remain which the PR may have missed:
> 
> https://github.com/numba/numba/blob/51fce0235e8b7ba1dc9ae41657c546a608b02847/numba/core/transforms.py#L114
> 
> https://github.com/numba/numba/blob/51fce0235e8b7ba1dc9ae41657c546a608b02847/numba/core/transforms.py#L188
> 
> And a few questions I've highlighted below

Thanks for the review. RE the changes above, I left those in as it was not at all clear that the condition can _only_ occur for 3.8 apart from what was in a comment from 7 years ago suggesting the case (there's no version guard in the code that will execute to prevent one or the other branch from running and there's nothing to suggest anyone has assessed this region with respect to other newer Python versions). I'm happy to try and remove it and then see if anything breaks on the Azure build, what do you think?

2023-11-29 14:16 UTC, stuartarchibald commented
RE: https://github.com/numba/numba/pull/9310#issuecomment-1831893159
I ran the looplifting tests (`numba.tests.test_looplifting`) on Python 3.12 and printed the line number and which condition was hit, result is this:
```
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS > 1
188: LOOP EXISTS > 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS > 1
188: LOOP EXISTS > 1
114: LOOP EXISTS == 1
114: LOOP EXISTS > 1
188: LOOP EXISTS > 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
114: LOOP EXISTS == 1
```
it looks like at least on 3.12 there are loops with exit count > 1, i.e. both branches are still in use. Can you replicate @kc611 ?

2023-11-29 14:52 UTC, stuartarchibald commented
Note: `py311_np126` failure is because I forgot to update the test count in the azure matrix config, it's now 18, not 21. Will fix.

2023-11-29 17:43 UTC, stuartarchibald commented
* e6eac03 removes the Python 3.8 specific commentary from `numba.core.transforms`.
* 19fc868 fixes the issue with the wrong number of test configurations declared in the Azure config.

2023-11-30 09:24 UTC, kc611 commented on numba/tests/test_builtins.py
> +        # In Python 3.8+ "start" can be specified as a kwarg, so test that too
We can leave it as-is, no problem.

2023-11-30 09:32 UTC, kc611 commented
> it looks like at least on 3.12 there are loops with exit count > 1, i.e. both branches are still in use. Can you replicate @kc611 ?

Yes, this can be replicated locally. As a result, the correct course of action is to simply leave the branches as-is and just modify the comments. (which has been done in e6eac03)

2023-11-30 15:53 UTC, sklam reviewed
one question

2023-11-30 15:59 UTC, esc commented on numba/tests/test_tuples.py
> +        # Python 3.9 has a peephole rewrite due to large changes in tuple
Is this 3.9 only or does it affect other Python versions too? If it is 3.9 only, perhaps it should go into a `if PYVERSION` block? If this is more Pythons then perhaps:

```suggestion
        # Python 3.9+ has a peephole rewrite due to large changes in tuple
```

2023-11-30 16:00 UTC, sklam commented on numba/core/transforms.py
>              [(returnto, _)] = cfg.successors(an_exit)  # requirement checked earlier
this was answered in https://github.com/numba/numba/pull/9310#issuecomment-1831978933

2023-11-30 16:00 UTC, sklam commented on numba/core/transforms.py
> +        # has multiple exits
this was answered in https://github.com/numba/numba/pull/9310#issuecomment-1831978933

2023-11-30 16:21 UTC, esc commented on numba/tests/test_tuples.py
> +        # Python 3.9 has a peephole rewrite due to large changes in tuple
As agreed with @stuartarchibald this will go into it's own PR.

2023-11-30 16:21 UTC, esc approved these changes
LGTM2

2023-11-30 16:21 UTC, merged