Add timing and junit xml output to testsuite
numba/numba pull request #9436
Opened 2024-02-13 21:47 UTC by sklam

2024-02-20 21:43 UTC, gmarkall commented
I tried clicking through to a test report (e.g. https://dev.azure.com/numba/numba/_TestManagement/Runs?runId=1926474&_a=runCharts) and I got a 401 (permission denied) error - are you able to access that? Do some permissions need changing somewhere?

2024-02-22 22:50 UTC, sklam commented
> I tried clicking through to a test report (e.g. https://dev.azure.com/numba/numba/_TestManagement/Runs?runId=1926474&_a=runCharts) and I got a 401 (permission denied) error - are you able to access that? Do some permissions need changing somewhere?

I finally figured it out. I need to enable "Test Plans" feature in the project settings. The link now works!
You can also find the xml files in the attachments.

2024-02-23 13:03 UTC, gmarkall commented
> > I tried clicking through to a test report (e.g. https://dev.azure.com/numba/numba/_TestManagement/Runs?runId=1926474&_a=runCharts) and I got a 401 (permission denied) error - are you able to access that? Do some permissions need changing somewhere?
> 
> I finally figured it out. I need to enable "Test Plans" feature in the project settings. The link now works! You can also find the xml files in the attachments.

I still get a 401 for that link :-(

2024-02-23 16:16 UTC, sklam commented
Can you see the attachment the "Tests" tab:

![Screenshot 2024-02-23 at 10 14 01 AM](https://github.com/numba/numba/assets/1929845/c51e0107-0bb8-458e-92fa-01e15a0ac443)

Need to click on a test run (e.g. "JUnit_TestResults_NNNN") in the table then click "attachments" on the right panel

2024-02-27 15:33 UTC, gmarkall commented
/azp run

2024-02-28 22:08 UTC, esc requested changes
Found a minor typo. Also, tried to log in to Azure to view the test results, as it appears as though I need to login to view them

This is what my screen looks like:

<img width="1231" alt="Screenshot 2024-02-28 at 23 08 02" src="https://github.com/numba/numba/assets/41563/85a907cd-48dc-4cf3-b563-376a68930db6">

2024-02-28 22:08 UTC, esc commented on numba/tests/test_runtests.py
> +        # If this raise the XML file is invalid
```suggestion
        # If this raises, the XML file is invalid
```

2024-02-28 22:10 UTC, esc commented
> Can you see the attachment the "Tests" tab:

Can you share more details about this screen and how to get there?

2024-02-29 14:13 UTC, esc commented
OK, so there are some UI contortions that one has to go through, in order to retrieve the file, but it does seem to be possible w/o logging in.

<img width="1217" alt="Screenshot 2024-02-29 at 15 13 23" src="https://github.com/numba/numba/assets/41563/4e9d63b8-8aee-4d2d-8e41-7411e9890305">

2024-02-29 16:40 UTC, esc approved these changes
Spellchecked and reviewed the code, looked at the generated RTD and worked out how to download and view the XML on azure.

LGTM

2024-02-29 18:49 UTC, esc approved these changes

2024-03-04 18:50 UTC, merged