Replace `context.compile_internal` by `context.call_overload`
numba/numba pull request #9516
Opened 2024-03-28 14:08 UTC by guilhermeleobas

This is more of an exploratory work, and it is not ready yet.

The idea is to replace all occurrences of `compile_internal` by `call_overload`, introduced in this PR. Some of the motivation for this change is the ability to use `print` inside compiled function and dynamic exceptions.

2024-03-28 15:18 UTC, guilhermeleobas commented
`acos` test fails with the following error:

```python
numba/core/lowering.py:1392: in lower_expr
    self.incref(resty, castval)
numba/core/lowering.py:1560: in incref
    self.context.nrt.incref(self.builder, typ, val)
numba/core/runtime/context.py:382: in incref
    self._call_incref_decref(builder, typ, value, "NRT_incref")
numba/core/runtime/context.py:367: in _call_incref_decref
    meminfos = self.get_meminfos(builder, typ, value)
numba/core/runtime/context.py:355: in get_meminfos
    field = getter(val)
numba/core/datamodel/models.py:713: in getter
    raise TypeError("expecting {0} but got {1}".format(*args))
E   TypeError: expecting {float, float} but got {double, double}
```

2024-04-08 09:57 UTC, gmarkall commented
Should this be moved from draft status now it's RFR?

2024-04-09 10:16 UTC, gmarkall commented
gpuci run tests

2024-04-09 11:00 UTC, gmarkall requested changes
Many thanks for the improvements! I've left some comments on the diff.

Unfortunately this seems to have broken CUDA ufuncs e.g. - https://gpuci.gpuopenanalytics.com/job/numba/job/numba/job/prb/job/numba-prb/675/CUDA_TOOLKIT_VER=11.8,CUDA_VER=11.2,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=21.12/console 

Do you need some help looking into the CUDA issue, or are you happy to fix this up?

2024-05-03 22:09 UTC, guilhermeleobas commented on numba/cpython/cmathimpl.py
> +    theargflt = z.underlying_float if isinstance(z, types.Complex) else z
Good catch! Thanks

2024-05-03 22:52 UTC, guilhermeleobas commented on numba/cpython/cmathimpl.py
> +def sqrt_impl(z):
There's one test in parfors that call `cmath.sqrt` with an integer. I think I remember why I included the code below:

```
     theargflt = z.underlying_float if isinstance(z, types.Complex) else z 
```

Should numba cast the integer to a complex value?

2024-05-07 13:44 UTC, gmarkall commented
gpuci run tests

2024-05-08 01:03 UTC, guilhermeleobas commented
The CI failure is probably related to one of the parfor tests calling `cmath.sqrt(integer)`

2024-05-08 15:05 UTC, guilhermeleobas commented
Calling any cmath function with a non-complex value should be valid. I'll create an issue to track this and change `cmath.sqrt` to accept non-complex inputs.

2024-05-13 14:52 UTC, guilhermeleobas commented
@gmarkall, could you run gpuci again on this PR?

2024-05-14 14:26 UTC, gmarkall commented
gpuci run tests

2024-05-14 14:54 UTC, guilhermeleobas commented
I think that this PR actually introduces a regression in Numba. Numba main branch currently supports calling any cmath function with a non-complex value, and this PR would prohibit that.

2024-05-16 22:01 UTC, gmarkall commented
gpuci run tests

2024-08-15 12:54 UTC, guilhermeleobas commented
I don't have the bandwidth to work on this one right now. Changed the label to `in progress`.

2024-12-03 02:04 UTC, closed without merging