Cherry-Pick: Merge pull request #9568 from esc/fix_parfors_test_sigabrt
numba/numba pull request #9617
Opened 2024-06-11 10:12 UTC by esc

fix sigabrt in parfors tests

Cherry-pick of #9568 for `main`

2024-06-11 10:13 UTC, esc commented
Build farm ID:  `Build numba_yaml_466 has started`

2024-06-14 13:55 UTC, kc611 requested changes

2024-06-14 13:55 UTC, kc611 commented on docs/source/release/0.60.0-notes.rst
> +* PR `#9568 <https://github.com/numba/numba/pull/9568>`_:  fix sigabrt in parfors tests (`esc <https://github.com/esc>` `stuartarchibald <https://github.com/stuartarchibald>`_)
```suggestion
* PR `#9568 <https://github.com/numba/numba/pull/9568>`_:  fix sigabrt in parfors tests (`esc <https://github.com/esc>`_ `stuartarchibald <https://github.com/stuartarchibald>`_)
```

And the same needs to be done for a line above this one.

2024-06-14 14:03 UTC, kc611 approved these changes

2024-06-14 14:19 UTC, kc611 approved these changes

2024-06-14 14:19 UTC, merged