Fix C99 `I` not working with NumPy 2.0.1
numba/numba pull request #9683
Opened 2024-08-02 15:53 UTC by sklam

Workaround problem with `I`

2024-08-02 16:06 UTC, sklam commented
BFID: `numba_smoketest_cpu_yaml_201`

2024-08-02 16:38 UTC, sklam commented
`numba_smoketest_cpu_yaml_201` not finished yet with test jobs but all build jobs have passed

2024-08-04 10:03 UTC, tiran commented
According to [The Open Group Base Specifications Issue 8](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/complex.h.html), you have to check for `_Imaginary_I` first and then fall back to `_Complex_I`, see https://github.com/numpy/numpy/issues/27083#issuecomment-2267389934

2024-08-06 11:18 UTC, gmarkall commented on numba/_helperlib.c
> +        #error "Lack _Imaginery_I and _Complex_I"
A small typo that might have a user grepping for something that will never be found:

```suggestion
        #error "Lack _Imaginary_I and _Complex_I"
```

2024-08-06 11:20 UTC, gmarkall requested changes
LGTM apart from the typo.

2024-08-06 14:20 UTC, gmarkall approved these changes

2024-08-06 21:30 UTC, sklam commented
CI problem fixed

2024-08-06 21:30 UTC, merged