Add `NUMBA_CACHE_OVERRIDE` to force caching on or off
numba/numba pull request #9702
Opened 2024-08-14 11:18 UTC by bcbnz

This adds a `NUMBA_CACHE_OVERRIDE` environment variable which is read into the `config.CACHE_OVERRIDE` setting. If set to ``always``, then the compilation decorators ignore the ``cache=`` parameter and always enable caching. If set to ``never``, then the decorators ignore the ``cache=`` parameter and always disable caching.

This closes #4549 where this variable and values were first suggested.

Note that I have added the override behavior to `numba.cuda.jit` but I currently don't have a CUDA setup to test this with. I assume the CI pipelines will take care of this -- if there is anything else I need to do to enable testing with CUDA, please let me know.

2024-08-20 14:24 UTC, gmarkall commented
gpuci run tests

2024-08-20 16:00 UTC, guilhermeleobas requested changes
Thanks for the contribution @bcbnz.

I'm ok with the changes, and we should also support this env var in `@vectorize`/`@guvectorize`, if possible.

The cuda part needs tests.

2025-02-14 01:57 UTC, closed without merging

2025-03-24 09:43 UTC, oren-hecht commented
Is there any plans for this to continue? I ran in to a separate issue regarding caching - while running a numba util in an AWS lambda function, the code crashes on
`[ERROR] RuntimeError: cannot cache function '_make_3d_series': no locator available`
probably since the environment does not have a readily available filesystem..

Also, in general, any serverless infrastructure like that will render caching meaningless anyways - so it would be nice to be able to disable the option

2025-03-24 12:47 UTC, gmarkall commented
@oren-hecht It looks like there has been no follow-up from the original submitter, so it's not planned at the moment. I think it could continue if someone else were to pick this up and resubmit as a new PR with changes incorporated for the feedback.

2026-02-04 11:15 UTC, heptaflar commented
What about setting `NUMBA_CACHE_DIR` to `/dev/null`? Would this effectively disable caching without breaking anything?