Revert RVSDG backend.
numba/numba pull request #9738
Opened 2024-10-01 21:35 UTC by sklam

Plan for RVSDG is to be developed into a separate pipeline.

2024-10-16 18:30 UTC, kc611 requested changes
I found the following references to RVSDG that need further removal:

- In the [azure-pipelines.yml](https://github.com/numba/numba/blob/b49469f06176769ecfa47a7865ef2030f4ed77f4/azure-pipelines.yml#L69)
- In the [meta.yml](https://github.com/numba/numba/blob/b49469f06176769ecfa47a7865ef2030f4ed77f4/buildscripts/condarecipe.local/meta.yaml#L64)

2024-10-16 20:27 UTC, sklam commented
@kc611 I've fixed those files. I'm minimizing the changes to azure config since we will need to update it very soon for new numpy and python.

2024-10-20 05:24 UTC, kc611 approved these changes

2024-10-20 05:24 UTC, kc611 approved these changes
LGTM!

2024-10-21 23:23 UTC, merged