Added changelog for `0.61.0` and updated release versioning table
numba/numba pull request #9800
Opened 2024-11-20 11:31 UTC by kc611

As titled, this PR adds changelog for `0.61.0` and update the release versioning table therein.

2024-11-20 12:50 UTC, gmarkall submitted a review, later dismissed
CUDA-related wording looks good.

2024-11-20 15:11 UTC, sklam commented on docs/source/release/0.61.0-notes.rst
> +=================================================
Wrong heading level

![Screenshot 2024-11-20 at 9 07 26 AM](https://github.com/user-attachments/assets/4eb64adf-1028-4283-9ab4-548dd26ebb52)

2024-11-20 15:11 UTC, sklam commented on docs/source/release/0.61.0-notes.rst
> +===============================================================================================================================
Wrong heading level

2024-11-20 15:11 UTC, sklam commented on docs/source/release/0.61.0-notes.rst
> +Python 3.13 support
Azure error: https://dev.azure.com/numba/numba/_build/results?buildId=18003&view=logs&j=92a5d2dc-b1c1-5fd3-be4c-f2c5b5a37a8d&t=e3dfe365-232a-52a4-3ae3-57b751ae31cd&l=177

2024-11-20 15:11 UTC, sklam commented on docs/source/release/0.61.0-notes.rst
> +=================================================
Link to page: https://numba--9800.org.readthedocs.build/en/9800/release-notes-overview.html

2024-11-20 16:19 UTC, sklam approved these changes

2024-11-20 16:39 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +- Add a config flag `USE_LEGACY_TYPE_SYSTEM` set to `1` (on) by default.
```suggestion
- Add a config flag ``USE_LEGACY_TYPE_SYSTEM`` set to ``1`` (on) by default.
```

2024-11-20 16:39 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +  Switching it to `0` (off) will activate new type system.
```suggestion
  Switching it to ``0`` (off) will activate new type system.
```

2024-11-20 16:39 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Functions decorated with `@guvectorize` can now be scheduled over distributed
```suggestion
Functions decorated with ``@guvectorize`` can now be scheduled over distributed
```

2024-11-20 16:40 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Fixed ``typed.List __repr__()`` to display ellipsis appropriately.
```suggestion
Fixed ``typed.List __repr__()`` to display ellipsis appropriately
```

2024-11-20 16:41 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Previously, the list repr would append the ellipsis at the end of the list
```suggestion
Previously, the list ``repr`` would append the ellipsis at the end of the list
```

2024-11-20 16:41 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +``find_topo_sort`` reliablilty improvement
```suggestion
``find_topo_sort`` reliabililty improvement
```

2024-11-20 16:43 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Fix parfor hoisting.
```suggestion
Fix parfor hoisting
```

2024-11-20 16:43 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +--------------------
```suggestion
-------------------
```

2024-11-20 16:43 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +-------------------------------------------------
```suggestion
------------------------------------------------
```

2024-11-20 16:44 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +------------------------------------------------------------------
```suggestion
-----------------------------------------------------------------
```

2024-11-20 16:45 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Add support for numpy 2.0 new function ``numpy.trapezoid``.
```suggestion
Add support for NumPy 2.0 new function ``numpy.trapezoid``.
```

2024-11-20 16:45 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Support for np.trapezoid
```suggestion
Support for ``np.trapezoid``
```

2024-11-20 16:45 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +------------------------
```suggestion
----------------------------
```

2024-11-20 16:47 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +------------------------------------------------
```suggestion
-----------------------------------------------
```

2024-11-20 16:47 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Fix regression in type-inference for star-arg arguments.
```suggestion
Fix regression in type-inference for star-arg arguments
```

2024-11-20 16:47 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +--------------------------------------------------------
```suggestion
-------------------------------------------------------
```

2024-11-20 16:49 UTC, esc commented on docs/source/user/installing.rst
> +| 0.61.0    | 2024-11-25   | 3.10.x <= version < 3.14  | 1.24 <= version < 1.27 ;                    | 0.44.x                       | 15.x              | 2021.6 <= version           |
```suggestion
| 0.61.0rc1 | 2024-11-25   | 3.10.x <= version < 3.14  | 1.24 <= version < 1.27 ;                    | 0.44.x                       | 15.x              | 2021.6 <= version           |
```

2024-11-20 16:51 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Schedule guvectorize'd functions over dask.distributed
```suggestion
Schedule guvectorize'd functions over ``dask.distributed``
```

2024-11-20 16:51 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +------------------------------------------------------
```suggestion
----------------------------------------------------------
```

2024-11-20 16:53 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Added support for np.setdiff1d(), np.setxor1d(), and np.in1d() functions, as well as argument assume_unique in np.intersect1d()
```suggestion
Added support for ``np.setdiff1d()``, ``np.setxor1d()``, and ``np.in1d()`` functions, as well as argument ``assume_unique`` in ``np.intersect1d()``
```

2024-11-20 16:53 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +-------------------------------------------------------------------------------------------------------------------------------
```suggestion
-------------------------------------------------------------------------------------------------------------------------------------------------
```

2024-11-20 16:53 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +-------------------------------------------------------------------------------------------------------------------------------
Please check the number of hyphens here after applying the suggestion, thanks. It should be 20.

2024-11-21 09:00 UTC, esc approved these changes
Second pass, clearing up all the things I missed during my first pass.

2024-11-21 09:00 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +Version 0.61.0 (25 November 2024)
```suggestion
Version 0.61.0rc1 (25 November 2024)
```

2024-11-21 09:00 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +=================================
```suggestion
====================================
```

2024-11-21 09:00 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +-------------------------------------------------------------------------------------------------------------------------------------------------
```suggestion
---------------------------------------------------------------------------------------------------------------------------------------------------
```

2024-11-21 09:00 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +------------------------------------------
```suggestion
-------------------------------------------
```

2024-11-21 09:00 UTC, esc requested changes
Sorry, wrong button during last review, still needs changes.

2024-11-21 09:01 UTC, esc commented on docs/source/release/0.61.0-notes.rst
> +------------------------------------------
This will fix the sphinx build error too.

2024-11-21 10:51 UTC, esc approved these changes
LGTM, I did another quick review and it looks fine.

2024-11-21 10:53 UTC, merged