Resolve mutable default argument problems
numba/numba pull request #9807
Opened 2024-11-23 09:14 UTC by EarlMilktea

Previously a part of #9793 , which is now more exhaustive and having restricted scopes.

2024-11-25 07:22 UTC, esc commented
@EarlMilktea thank your for following up on this. To quote my comment from https://github.com/numba/numba/pull/9793#issuecomment-2486037380 :

> We don't want to change the signature of the decorator, since this would indicate a change to the public API. This has
> been attempted before and the suggestion is to keep {} in the signature and wrap the locals in a MappingProxyType. There > is a suggestion here about how to do this: https://github.com/numba/numba/pull/5811#issuecomment-653614543

Essentially, because some of these functions are public interfaces, the conclusion from the developer meeting was that we can not change the value of the defaults. I.e. we need to maintain our violation of the best practices and we need to keep the mutable containers in the default arguments of the functions. This is an unfortunate truth, which we can not change anymore. The idea instead is to modify the function and wrap the argument in a `types.MappingProxyType` -- this will signify that the object is supposed to be read-only and should warn if the argument is being modified. 

So, essentially, instead of:

```
    if locals is None:
        locals = {}
```

We need:

```
    locals = MappingProxyType(locals)
```

At least this is the case for the `@njit` and `@cfunc` decorators as these were the only two that had been modified in your original PR.

Since you went ahead and modified all the cases of default values using mutable arguments,  I don't yet know what to do about all the other modifications. We will discuss this during a next developer meeting and I will get back to you.

2024-11-25 10:49 UTC, EarlMilktea commented
@esc Could you explicitly specify the places that should not be modified after meeting?

2024-11-25 11:40 UTC, gmarkall commented
Some history is in https://github.com/numba/numba/pull/5811 which I think provides some pointers.

2024-11-25 11:41 UTC, gmarkall commented
gpuci run tests

2024-11-27 10:37 UTC, gmarkall approved these changes
I approve of this from the CUDA side - it appears to fix a genuine issue whereby the list of files to link will include the `cpp_function_wrappers.cu` file for every kernel defined after a kernel that uses float16s has been compiled.

2024-11-27 14:30 UTC, esc commented
> @esc Could you explicitly specify the places that should not be modified after meeting?

Yes! So everything that is considered a public interface, for example `cfunc` and `njit` need the `MappingProxyType` variant. So probably start with those. For anything non public, the community is willing to accept the change from `{}` to `None` and `[]` to `None`.

Also, we kindly request that you rebase this PR to remove the emojis in the commit messages. We have had issues with these in the past when building on windows systems. Thank you.

2024-11-27 14:34 UTC, esc requested changes
Pointing to the public interfaces that need the special variant.

2024-11-27 14:34 UTC, esc commented on numba/core/decorators.py
> +def jit(signature_or_function=None, locals=None, cache=False,
This needs the `MappingProxyType` variant.

2024-11-27 14:34 UTC, esc commented on numba/core/decorators.py
> +def cfunc(sig, locals=None, cache=False, pipeline_class=None, **options):
This needs the MappingProxyType variant.

2024-11-27 14:34 UTC, esc commented on numba/core/extending.py
> +def overload(func, jit_options=None, strict=True, inline='never',
This needs the MappingProxyType variant.

2024-11-28 05:29 UTC, EarlMilktea commented
> you rebase this PR to remove the emojis in the commit messages

Sure, but I would like note that these emojis are in fact just simple ascii chars (something like :emoji:, github automatically render them) so it may have to be considered as a bug if the build system is incompatible with them.

2024-11-30 15:10 UTC, EarlMilktea commented
By the way, are you maintainers interested in checking mutable default problems by linter?
This can be achieved `flake8-bugbear` or `ruff` .

2024-12-03 17:40 UTC, esc commented
@EarlMilktea thank you for your patience here. During the developer meeting we found consensus for a solution to this.

The code in question can be modified as follows:

Do the cast to the `MappingProxyType` in the kwarg:

```
      def func(locals=MappingProxyType({})):
```

And then let the first line of the body be:

```
          locals = dict(locals)
```

That way, we preserve the type of the input to be a mapping and also copy construct a dict that can be modified by code further downstream.

I think that will be suitable and should also solve the bug you have identified with the current variant of this patch! Thank you!

2024-12-05 10:10 UTC, esc commented
> @esc
> 
> I'm now struggling to understand why this approach is better than `=None`.
> 
> ```python
> def func(locals=MappingProxyType({})):
> ```
> 
> If I remember correctly the reason why we cannot use `=None` here is backward compatibility, but with the above users can see the change. If it's acceptable, there is no reason for using `=MappingProxyType({})` here because there're many other ways to maintain singleton dict, for example:
> 
> ```python
> @functools.cache
> def _mem():
>     return {}
> ```
> 
> This approach can be combined with `=None`, which is the most idiomatic and safe way to represent mutable defaults.

Thank you for voicing your concerns here. I will revisit this issue again during the developer meeting next week and get back to you with an answer.

For now: from what I understand using `None` will lead to a type change of the top-level function, which leads to a signature change in a stable API. Instead of the argument being of type `mapping` it would be an `optional` that can be either `mapping` or `None`, this is what we are trying to avoid. While using `None` is the most natural and best solution in this case -- you are not wrong about that -- the development community is not willing to accept this change and would like to find alternative solutions to maintain the stability of the public API.

2024-12-05 12:19 UTC, EarlMilktea commented
> type change of the top-level function

I see. I agree your suggestion is the best solution for this PR if the signature itself should not be changed. Thank you for kind explanation!

@esc Can I apply this suggestion right now or should I wait for the next meeting?

```py
def func(locals=MappingProxyType({})): ...
```

2024-12-05 15:10 UTC, esc commented
> > type change of the top-level function
> 
> I see. I agree your suggestion is the best solution for this PR if the signature itself should not be changed. Thank you for kind explanation!
> 
> @esc Can I apply this suggestion right now or should I wait for the next meeting?
> 
> ```python
> def func(locals=MappingProxyType({})): ...
> ```

Yes, you can apply this change to the few cases that apply.

2024-12-05 15:47 UTC, EarlMilktea commented
Done. Everything is ready now.

2024-12-05 15:53 UTC, esc requested changes
Need to fix the `flake8` issue reported:

numba/core/extending.py:63:81: E501 line too long (81 > 80 characters)

2024-12-05 16:22 UTC, EarlMilktea commented
Oops, fixed.

2024-12-05 18:07 UTC, esc approved these changes
LGTM

2025-01-14 16:24 UTC, esc commented
Thank you for the patch!

2025-01-14 16:24 UTC, merged