[WIP]Fall back on inspect.getsourcelines() in first line finder
numba/numba pull request #9861
Opened 2024-12-20 18:12 UTC by gmarkall

This enables lineinfo to be produced for cells in Jupyter notebooks.

This has been tested with a kernel in source in a .py file and the same in a Jupyter notebook, with `lineinfo=True` - these two cases produce PTX with identical lineinfo (`.loc` directives).

WIP as tests need to be added, and further experimentation / testing.

Fixes #9835.

2025-01-14 20:43 UTC, sklam requested changes

2025-01-14 20:43 UTC, sklam commented on numba/misc/firstlinefinder.py
> +            source = "".join(lines)
```suggestion
            source = "\n".join(lines)
```
`lines` doesn't contain the new line chars.

2025-01-14 20:43 UTC, sklam commented on numba/tests/test_firstlinefinder.py
> +        """
i am testing it with:
```python
        source = """if True:
        # indent causes IndentationError in ast.parse

        def decor(f):
            return f

        @decor 
        @decor
        @decor
        def foo():
            pass
        """
```
indentation is not handled. As `ast.parse()` is seeing:

```python
        @decor  # nested decorators work fine
        @decor
        @decor
        def foo():
            pass
```

2025-01-14 20:43 UTC, sklam commented on numba/misc/firstlinefinder.py
> +            source = "".join(lines)
The reason i didn't use `getsourcelines()` might just be my reluntance to handle indentation. If you add that logic, we might not need to read from `co.co_filename` ourselves.

2025-01-15 22:45 UTC, sklam commented on numba/tests/test_firstlinefinder.py
> +        entry = (len(source), timestamp, source.splitlines(), filename)
```suggestion
        entry = (len(source), timestamp, source.splitlines(True), filename)
```
keepends for linecache

2025-01-16 12:26 UTC, gmarkall commented on numba/tests/test_firstlinefinder.py
> +        """
Thanks - I've added some tests now that do something similar.

2025-01-16 12:28 UTC, gmarkall commented on numba/misc/firstlinefinder.py
> +            source = "".join(lines)
Thanks for the insight - I've added dedentation, which seems to work, but I think I'd feel more comfortable with `inspect.getsourcelines()` as the fallback for now, then once it's been used a bit in the wild to determine if there are other issues or if it's pretty stable, I'd then be happy with using `getsourcelines()` as the main / only method.

2025-01-16 12:29 UTC, gmarkall commented
@sklam Many thanks for the review - as far as I can see, dedenting the source from `getsourcelines()` seems to do the job, and I've added a few tests that seem to be OK with this tactic. What do you think of this approach? Can you think of other cases that could be missing?

2025-01-20 16:09 UTC, sklam approved these changes
This is good for now. Agree to use `.getsourcelines()` as fallback until it has been proven  to work without issues.

2025-01-21 17:45 UTC, merged